In [353]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [354]:
sample = pd.read_csv('sample_submission.csv')
sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 2 columns):
Id           1459 non-null int64
SalePrice    1459 non-null float64
dtypes: float64(1), int64(1)
memory usage: 22.9 KB

In [355]:
train = pd.read_csv('train_kaggle.csv')
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [356]:
test = pd.read_csv('test_kaggle.csv')
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
Id               1459 non-null int64
MSSubClass       1459 non-null int64
MSZoning         1455 non-null object
LotFrontage      1232 non-null float64
LotArea          1459 non-null int64
Street           1459 non-null object
Alley            107 non-null object
LotShape         1459 non-null object
LandContour      1459 non-null object
Utilities        1457 non-null object
LotConfig        1459 non-null object
LandSlope        1459 non-null object
Neighborhood     1459 non-null object
Condition1       1459 non-null object
Condition2       1459 non-null object
BldgType         1459 non-null object
HouseStyle       1459 non-null object
OverallQual      1459 non-null int64
OverallCond      1459 non-null int64
YearBuilt        1459 non-null int64
YearRemodAdd     1459 non-null int64
RoofStyle        1459 non-null object
RoofMatl         1459 non-null object
Exterior1st      1458 non-null object
Exterior2nd      1458 non-null object
MasVnrType       1443 non-null object
MasVnrArea       1444 non-null float64
ExterQual        1459 non-null object
ExterCond        1459 non-null object
Foundation       1459 non-null object
BsmtQual         1415 non-null object
BsmtCond         1414 non-null object
BsmtExposure     1415 non-null object
BsmtFinType1     1417 non-null object
BsmtFinSF1       1458 non-null float64
BsmtFinType2     1417 non-null object
BsmtFinSF2       1458 non-null float64
BsmtUnfSF        1458 non-null float64
TotalBsmtSF      1458 non-null float64
Heating          1459 non-null object
HeatingQC        1459 non-null object
CentralAir       1459 non-null object
Electrical       1459 non-null object
1stFlrSF         1459 non-null int64
2ndFlrSF         1459 non-null int64
LowQualFinSF     1459 non-null int64
GrLivArea        1459 non-null int64
BsmtFullBath     1457 non-null float64
BsmtHalfBath     1457 non-null float64
FullBath         1459 non-null int64
HalfBath         1459 non-null int64
BedroomAbvGr     1459 non-null int64
KitchenAbvGr     1459 non-null int64
KitchenQual      1458 non-null object
TotRmsAbvGrd     1459 non-null int64
Functional       1457 non-null object
Fireplaces       1459 non-null int64
FireplaceQu      729 non-null object
GarageType       1383 non-null object
GarageYrBlt      1381 non-null float64
GarageFinish     1381 non-null object
GarageCars       1458 non-null float64
GarageArea       1458 non-null float64
GarageQual       1381 non-null object
GarageCond       1381 non-null object
PavedDrive       1459 non-null object
WoodDeckSF       1459 non-null int64
OpenPorchSF      1459 non-null int64
EnclosedPorch    1459 non-null int64
3SsnPorch        1459 non-null int64
ScreenPorch      1459 non-null int64
PoolArea         1459 non-null int64
PoolQC           3 non-null object
Fence            290 non-null object
MiscFeature      51 non-null object
MiscVal          1459 non-null int64
MoSold           1459 non-null int64
YrSold           1459 non-null int64
SaleType         1458 non-null object
SaleCondition    1459 non-null object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [357]:
data = train.append(test)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 81 columns):
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
3SsnPorch        2919 non-null int64
Alley            198 non-null object
BedroomAbvGr     2919 non-null int64
BldgType         2919 non-null object
BsmtCond         2837 non-null object
BsmtExposure     2837 non-null object
BsmtFinSF1       2918 non-null float64
BsmtFinSF2       2918 non-null float64
BsmtFinType1     2840 non-null object
BsmtFinType2     2839 non-null object
BsmtFullBath     2917 non-null float64
BsmtHalfBath     2917 non-null float64
BsmtQual         2838 non-null object
BsmtUnfSF        2918 non-null float64
CentralAir       2919 non-null object
Condition1       2919 non-null object
Condition2       2919 non-null object
Electrical       2918 non-null object
EnclosedPorch    2919 non-null int64
ExterCond        2919 non-null object
ExterQual        2919 non-null object
Exterior1st      2918 non-null object
Exterior2nd      2918 non-null object
Fence            571 non-null object
FireplaceQu      1499 non-null object
Fireplaces       2919 non-null int64
Foundation       2919 non-null object
FullBath         2919 non-null int64
Functional       2917 non-null object
GarageArea       2918 non-null float64
GarageCars       2918 non-null float64
GarageCond       2760 non-null object
GarageFinish     2760 non-null object
GarageQual       2760 non-null object
GarageType       2762 non-null object
GarageYrBlt      2760 non-null float64
GrLivArea        2919 non-null int64
HalfBath         2919 non-null int64
Heating          2919 non-null object
HeatingQC        2919 non-null object
HouseStyle       2919 non-null object
Id               2919 non-null int64
KitchenAbvGr     2919 non-null int64
KitchenQual      2918 non-null object
LandContour      2919 non-null object
LandSlope        2919 non-null object
LotArea          2919 non-null int64
LotConfig        2919 non-null object
LotFrontage      2433 non-null float64
LotShape         2919 non-null object
LowQualFinSF     2919 non-null int64
MSSubClass       2919 non-null int64
MSZoning         2915 non-null object
MasVnrArea       2896 non-null float64
MasVnrType       2895 non-null object
MiscFeature      105 non-null object
MiscVal          2919 non-null int64
MoSold           2919 non-null int64
Neighborhood     2919 non-null object
OpenPorchSF      2919 non-null int64
OverallCond      2919 non-null int64
OverallQual      2919 non-null int64
PavedDrive       2919 non-null object
PoolArea         2919 non-null int64
PoolQC           10 non-null object
RoofMatl         2919 non-null object
RoofStyle        2919 non-null object
SaleCondition    2919 non-null object
SalePrice        1460 non-null float64
SaleType         2918 non-null object
ScreenPorch      2919 non-null int64
Street           2919 non-null object
TotRmsAbvGrd     2919 non-null int64
TotalBsmtSF      2918 non-null float64
Utilities        2917 non-null object
WoodDeckSF       2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
YrSold           2919 non-null int64
dtypes: float64(12), int64(26), object(43)
memory usage: 1.8+ MB

/Users/charliecarrera/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)

In [358]:
1459*2

2918

In [359]:
O_type = data['BldgType'].dtype

In [360]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 81 columns):
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
3SsnPorch        2919 non-null int64
Alley            198 non-null object
BedroomAbvGr     2919 non-null int64
BldgType         2919 non-null object
BsmtCond         2837 non-null object
BsmtExposure     2837 non-null object
BsmtFinSF1       2918 non-null float64
BsmtFinSF2       2918 non-null float64
BsmtFinType1     2840 non-null object
BsmtFinType2     2839 non-null object
BsmtFullBath     2917 non-null float64
BsmtHalfBath     2917 non-null float64
BsmtQual         2838 non-null object
BsmtUnfSF        2918 non-null float64
CentralAir       2919 non-null object
Condition1       2919 non-null object
Condition2       2919 non-null object
Electrical       2918 non-null object
EnclosedPorch    2919 non-null int64
ExterCond        2919 non-null object
ExterQual        2919 non-null object
Exterior1st      2918 non-null object
Exterior2nd      2918 non-null object
Fence            571 non-null object
FireplaceQu      1499 non-null object
Fireplaces       2919 non-null int64
Foundation       2919 non-null object
FullBath         2919 non-null int64
Functional       2917 non-null object
GarageArea       2918 non-null float64
GarageCars       2918 non-null float64
GarageCond       2760 non-null object
GarageFinish     2760 non-null object
GarageQual       2760 non-null object
GarageType       2762 non-null object
GarageYrBlt      2760 non-null float64
GrLivArea        2919 non-null int64
HalfBath         2919 non-null int64
Heating          2919 non-null object
HeatingQC        2919 non-null object
HouseStyle       2919 non-null object
Id               2919 non-null int64
KitchenAbvGr     2919 non-null int64
KitchenQual      2918 non-null object
LandContour      2919 non-null object
LandSlope        2919 non-null object
LotArea          2919 non-null int64
LotConfig        2919 non-null object
LotFrontage      2433 non-null float64
LotShape         2919 non-null object
LowQualFinSF     2919 non-null int64
MSSubClass       2919 non-null int64
MSZoning         2915 non-null object
MasVnrArea       2896 non-null float64
MasVnrType       2895 non-null object
MiscFeature      105 non-null object
MiscVal          2919 non-null int64
MoSold           2919 non-null int64
Neighborhood     2919 non-null object
OpenPorchSF      2919 non-null int64
OverallCond      2919 non-null int64
OverallQual      2919 non-null int64
PavedDrive       2919 non-null object
PoolArea         2919 non-null int64
PoolQC           10 non-null object
RoofMatl         2919 non-null object
RoofStyle        2919 non-null object
SaleCondition    2919 non-null object
SalePrice        1460 non-null float64
SaleType         2918 non-null object
ScreenPorch      2919 non-null int64
Street           2919 non-null object
TotRmsAbvGrd     2919 non-null int64
TotalBsmtSF      2918 non-null float64
Utilities        2917 non-null object
WoodDeckSF       2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
YrSold           2919 non-null int64
dtypes: float64(12), int64(26), object(43)
memory usage: 1.8+ MB

In [361]:
object_columns = [column for column in data.columns if data[column].dtype == data['BldgType'].dtype]

In [362]:
data_object = pd.DataFrame()

In [363]:
for name in object_columns:
    data_object[name] = data[name]

In [364]:
data_object.describe()

,Alley,BldgType,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,BsmtQual,CentralAir,Condition1,Condition2,...,MiscFeature,Neighborhood,PavedDrive,PoolQC,RoofMatl,RoofStyle,SaleCondition,SaleType,Street,Utilities
count,198,2919,2837,2837,2840,2839,2838,2919,2919,2919,...,105,2919,2919,10,2919,2919,2919,2918,2919,2917
unique,2,5,4,4,6,6,4,2,9,8,...,4,25,3,3,8,6,6,9,2,2
top,Grvl,1Fam,TA,No,Unf,Unf,TA,Y,Norm,Norm,...,Shed,NAmes,Y,Ex,CompShg,Gable,Normal,WD,Pave,AllPub
freq,120,2425,2606,1904,851,2493,1283,2723,2511,2889,...,95,443,2641,4,2876,2310,2402,2525,2907,2916

In [365]:
for column in object_columns:
    data[column] = data[column].replace(data[column].unique(), range(len(data[column].unique())))

In [366]:
train['GarageType'].unique()

array(['Attchd', 'Detchd', 'BuiltIn', 'CarPort', nan, 'Basment', '2Types'],
      dtype=object)

In [367]:
range(len(train['GarageType'].unique()))

range(0, 7)

In [368]:
data['GarageType'].unique()

array([0, 1, 2, 3, 4, 5, 6])

In [369]:
data['GarageType']

0       0
1       0
2       0
3       1
4       0
5       0
6       0
7       0
8       1
9       0
10      1
11      2
12      1
13      0
14      0
15      1
16      0
17      3
18      1
19      0
20      2
21      0
22      0
23      0
24      0
25      0
26      1
27      0
28      0
29      1
       ..
1429    1
1430    1
1431    4
1432    4
1433    4
1434    0
1435    0
1436    0
1437    6
1438    0
1439    0
1440    0
1441    0
1442    0
1443    0
1444    0
1445    0
1446    2
1447    0
1448    6
1449    4
1450    0
1451    0
1452    3
1453    4
1454    4
1455    3
1456    1
1457    4
1458    0
Name: GarageType, Length: 2919, dtype: int64

In [370]:
del data['Alley']
del data['PoolQC']

In [371]:
data.describe()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,BsmtFinType1,...,SaleType,ScreenPorch,Street,TotRmsAbvGrd,TotalBsmtSF,Utilities,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,2919.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000
mean,1159.581706,336.483727,2.602261,2.860226,0.460774,0.211716,0.800274,441.423235,49.582248,1.846523,...,0.251799,16.062350,0.004111,6.451524,1051.777587,0.001713,93.709832,1971.312778,1984.264474,2007.792737
std,392.362079,428.701456,25.188169,0.822693,1.088487,0.676432,1.233050,455.610826,169.205611,1.686056,...,0.856761,56.184365,0.063996,1.569379,440.766258,0.055510,126.526589,30.291442,20.894344,1.314964
min,334.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1872.000000,1950.000000,2006.000000
25%,876.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,5.000000,793.000000,0.000000,0.000000,1953.500000,1965.000000,2007.000000
50%,1082.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,368.500000,0.000000,2.000000,...,0.000000,0.000000,0.000000,6.000000,989.500000,0.000000,0.000000,1973.000000,1993.000000,2008.000000
75%,1387.500000,704.000000,0.000000,3.000000,0.000000,0.000000,2.000000,733.000000,0.000000,3.000000,...,0.000000,0.000000,0.000000,7.000000,1302.000000,0.000000,168.000000,2001.000000,2004.000000,2009.000000
max,5095.000000,2065.000000,508.000000,8.000000,4.000000,4.000000,4.000000,5644.000000,1526.000000,6.000000,...,9.000000,576.000000,1.000000,15.000000,6110.000000,2.000000,1424.000000,2010.000000,2010.000000,2010.000000

In [372]:
data['GarageYrBlt'][data['GarageYrBlt'] > 2018]

1132    2207.0
Name: GarageYrBlt, dtype: float64

In [373]:
#Entry with garage built in the future (in year 2207) says house was built in 2006
#Make outlier equal to 2007
data['GarageYrBlt'][data['GarageYrBlt'] > 2018] = 2007

/Users/charliecarrera/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [374]:
#Change Year variables, 0 is newest year possible, higher number = older house
k = ['YrSold', 'GarageYrBlt', 'YearBuilt', 'YearRemodAdd']
for column in k:
    data[column] = [(2018 - i) for i in data[column]]

In [375]:
data[k].describe()

            YrSold  GarageYrBlt    YearBuilt  YearRemodAdd
count  2919.000000  2760.000000  2919.000000   2919.000000
mean     10.207263    39.959058    46.687222     33.735526
std       1.314964    25.206206    30.291442     20.894344
min       8.000000     8.000000     8.000000      8.000000
25%       9.000000    16.000000    17.000000     14.000000
50%      10.000000    39.000000    45.000000     25.000000
75%      11.000000    58.000000    64.500000     53.000000
max      12.000000   123.000000   146.000000     68.000000

In [376]:
np.std(data['1stFlrSF'])

392.2948646055113

In [377]:
data1 = data
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 79 columns):
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
3SsnPorch        2919 non-null int64
BedroomAbvGr     2919 non-null int64
BldgType         2919 non-null int64
BsmtCond         2919 non-null int64
BsmtExposure     2919 non-null int64
BsmtFinSF1       2918 non-null float64
BsmtFinSF2       2918 non-null float64
BsmtFinType1     2919 non-null int64
BsmtFinType2     2919 non-null int64
BsmtFullBath     2917 non-null float64
BsmtHalfBath     2917 non-null float64
BsmtQual         2919 non-null int64
BsmtUnfSF        2918 non-null float64
CentralAir       2919 non-null int64
Condition1       2919 non-null int64
Condition2       2919 non-null int64
Electrical       2919 non-null int64
EnclosedPorch    2919 non-null int64
ExterCond        2919 non-null int64
ExterQual        2919 non-null int64
Exterior1st      2919 non-null int64
Exterior2nd      2919 non-null int64
Fence            2919 non-null int64
FireplaceQu      2919 non-null int64
Fireplaces       2919 non-null int64
Foundation       2919 non-null int64
FullBath         2919 non-null int64
Functional       2919 non-null int64
GarageArea       2918 non-null float64
GarageCars       2918 non-null float64
GarageCond       2919 non-null int64
GarageFinish     2919 non-null int64
GarageQual       2919 non-null int64
GarageType       2919 non-null int64
GarageYrBlt      2760 non-null float64
GrLivArea        2919 non-null int64
HalfBath         2919 non-null int64
Heating          2919 non-null int64
HeatingQC        2919 non-null int64
HouseStyle       2919 non-null int64
Id               2919 non-null int64
KitchenAbvGr     2919 non-null int64
KitchenQual      2919 non-null int64
LandContour      2919 non-null int64
LandSlope        2919 non-null int64
LotArea          2919 non-null int64
LotConfig        2919 non-null int64
LotFrontage      2433 non-null float64
LotShape         2919 non-null int64
LowQualFinSF     2919 non-null int64
MSSubClass       2919 non-null int64
MSZoning         2919 non-null int64
MasVnrArea       2896 non-null float64
MasVnrType       2919 non-null int64
MiscFeature      2919 non-null int64
MiscVal          2919 non-null int64
MoSold           2919 non-null int64
Neighborhood     2919 non-null int64
OpenPorchSF      2919 non-null int64
OverallCond      2919 non-null int64
OverallQual      2919 non-null int64
PavedDrive       2919 non-null int64
PoolArea         2919 non-null int64
RoofMatl         2919 non-null int64
RoofStyle        2919 non-null int64
SaleCondition    2919 non-null int64
SalePrice        1460 non-null float64
SaleType         2919 non-null int64
ScreenPorch      2919 non-null int64
Street           2919 non-null int64
TotRmsAbvGrd     2919 non-null int64
TotalBsmtSF      2918 non-null float64
Utilities        2919 non-null int64
WoodDeckSF       2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
YrSold           2919 non-null int64
dtypes: float64(12), int64(67)
memory usage: 1.8 MB

In [378]:
#Normalize:
#x-min/xmax-xmin
#0 to 1 scale

In [379]:
is_null = [column for column in data1.columns if data1[column].isnull().sum() > 0]

In [380]:
is_null_less = [column for column in data1[is_null].columns if data1[column].isnull().sum() < 10]

In [381]:
data1[is_null].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 12 columns):
BsmtFinSF1      2918 non-null float64
BsmtFinSF2      2918 non-null float64
BsmtFullBath    2917 non-null float64
BsmtHalfBath    2917 non-null float64
BsmtUnfSF       2918 non-null float64
GarageArea      2918 non-null float64
GarageCars      2918 non-null float64
GarageYrBlt     2760 non-null float64
LotFrontage     2433 non-null float64
MasVnrArea      2896 non-null float64
SalePrice       1460 non-null float64
TotalBsmtSF     2918 non-null float64
dtypes: float64(12)
memory usage: 296.5 KB

In [382]:
data1['BsmtFinSF1'].mean()

441.4232350925291

In [383]:
data1[is_null]

,BsmtFinSF1,BsmtFinSF2,BsmtFullBath,BsmtHalfBath,BsmtUnfSF,GarageArea,GarageCars,GarageYrBlt,LotFrontage,MasVnrArea,SalePrice,TotalBsmtSF
0,706.0,0.0,1.0,0.0,150.0,548.0,2.0,15.0,65.0,196.0,208500.0,856.0
1,978.0,0.0,0.0,1.0,284.0,460.0,2.0,42.0,80.0,0.0,181500.0,1262.0
2,486.0,0.0,1.0,0.0,434.0,608.0,2.0,17.0,68.0,162.0,223500.0,920.0
3,216.0,0.0,1.0,0.0,540.0,642.0,3.0,20.0,60.0,0.0,140000.0,756.0
4,655.0,0.0,1.0,0.0,490.0,836.0,3.0,18.0,84.0,350.0,250000.0,1145.0
5,732.0,0.0,1.0,0.0,64.0,480.0,2.0,25.0,85.0,0.0,143000.0,796.0
6,1369.0,0.0,1.0,0.0,317.0,636.0,2.0,14.0,75.0,186.0,307000.0,1686.0
7,859.0,32.0,1.0,0.0,216.0,484.0,2.0,45.0,NaN,240.0,200000.0,1107.0
8,0.0,0.0,0.0,0.0,952.0,468.0,2.0,87.0,51.0,0.0,129900.0,952.0
9,851.0,0.0,1.0,0.0,140.0,205.0,1.0,79.0,50.0,0.0,118000.0,991.0
10,906.0,0.0,1.0,0.0,134.0,384.0,1.0,53.0,70.0,0.0,129500.0,1040.0
11,998.0,0.0,1.0,0.0,177.0,736.0,3.0,13.0,85.0,286.0,345000.0,1175.0
12,737.0,0.0,1.0,0.0,175.0,352.0,1.0,56.0,NaN,0.0,144000.0,912.0
13,0.0,0.0,0.0,0.0,1494.0,840.0,3.0,12.0,91.0,306.0,279500.0,1494.0
14,733.0,0.0,1.0,0.0,520.0,352.0,1.0,58.0,NaN,212.0,157000.0,1253.0
15,0.0,0.0,0.0,0.0,832.0,576.0,2.0,27.0,51.0,0.0,132000.0,832.0
16,578.0,0.0,1.0,0.0,426.0,480.0,2.0,48.0,NaN,180.0,149000.0,1004.0
17,0.0,0.0,0.0,0.0,0.0,516.0,2.0,51.0,72.0,0.0,90000.0,0.0
18,646.0,0.0,1.0,0.0,468.0,576.0,2.0,14.0,66.0,0.0,159000.0,1114.0
19,504.0,0.0,0.0,0.0,525.0,294.0,1.0,60.0,70.0,0.0,139000.0,1029.0
20,0.0,0.0,0.0,0.0,1158.0,853.0,3.0,13.0,101.0,380.0,325300.0,1158.0
21,0.0,0.0,0.0,0.0,637.0,280.0,1.0,88.0,57.0,0.0,139400.0,637.0
22,0.0,0.0,0.0,0.0,1777.0,534.0,2.0,16.0,75.0,281.0,230000.0,1777.0
23,840.0,0.0,1.0,0.0,200.0,572.0,2.0,42.0,44.0,0.0,129900.0,1040.0
24,188.0,668.0,1.0,0.0,204.0,270.0,1.0,50.0,NaN,0.0,154000.0,1060.0
25,0.0,0.0,0.0,0.0,1566.0,890.0,3.0,11.0,110.0,640.0,256300.0,1566.0
26,234.0,486.0,0.0,1.0,180.0,576.0,2.0,13.0,60.0,0.0,134800.0,900.0
27,1218.0,0.0,1.0,0.0,486.0,772.0,3.0,10.0,98.0,200.0,306000.0,1704.0
28,1277.0,0.0,1.0,0.0,207.0,319.0,1.0,61.0,47.0,0.0,207500.0,1484.0
29,0.0,0.0,0.0,0.0,520.0,240.0,1.0,98.0,60.0,0.0,68500.0,520.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1429,0.0,0.0,0.0,0.0,641.0,272.0,1.0,93.0,50.0,0.0,NaN,641.0
1430,0.0,0.0,0.0,0.0,967.0,384.0,1.0,61.0,75.0,327.0,NaN,967.0
1431,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,69.0,0.0,NaN,0.0
1432,0.0,0.0,0.0,0.0,660.0,0.0,0.0,NaN,50.0,0.0,NaN,660.0
1433,0.0,0.0,0.0,0.0,216.0,0.0,0.0,NaN,60.0,0.0,NaN,216.0
1434,1573.0,0.0,2.0,0.0,0.0,495.0,2.0,13.0,41.0,473.0,NaN,1573.0
1435,1564.0,0.0,1.0,1.0,30.0,525.0,2.0,14.0,44.0,186.0,NaN,1594.0
1436,776.0,0.0,0.0,1.0,849.0,576.0,2.0,39.0,69.0,0.0,NaN,1625.0
1437,0.0,0.0,0.0,0.0,1664.0,616.0,2.0,40.0,65.0,0.0,NaN,1664.0
1438,0.0,0.0,0.0,0.0,1491.0,490.0,2.0,17.0,70.0,0.0,NaN,1491.0
1439,576.0,0.0,1.0,0.0,552.0,528.0,2.0,43.0,140.0,257.0,NaN,1128.0
1440,909.0,0.0,1.0,0.0,723.0,518.0,2.0,60.0,NaN,0.0,NaN,1632.0
1441,1136.0,116.0,1.0,0.0,129.0,470.0,2.0,18.0,NaN,0.0,NaN,1381.0
1442,1350.0,0.0,1.0,0.0,378.0,714.0,3.0,13.0,95.0,198.0,NaN,1728.0
1443,1455.0,0.0,1.0,0.0,383.0,682.0,3.0,13.0,88.0,382.0,NaN,1838.0
1444,0.0,0.0,0.0,0.0,0.0,270.0,1.0,67.0,125.0,0.0,NaN,0.0
1445,1243.0,0.0,2.0,0.0,45.0,784.0,4.0,21.0,78.0,200.0,NaN,1288.0
1446,0.0,0.0,0.0,0.0,264.0,336.0,1.0,41.0,41.0,0.0,NaN,264.0
1447,441.0,0.0,1.0,0.0,423.0,288.0,1.0,50.0,58.0,0.0,NaN,864.0
1448,149.0,0.0,0.0,0.0,1503.0,928.0,3.0,48.0,NaN,0.0,NaN,1652.0
1449,522.0,0.0,1.0,0.0,108.0,0.0,0.0,NaN,21.0,0.0,NaN,630.0
1450,252.0,0.0,0.0,0.0,294.0,253.0,1.0,46.0,21.0,0.0,NaN,546.0
1451,119.0,344.0,1.0,0.0,641.0,336.0,1.0,49.0,80.0,194.0,NaN,1104.0
1452,408.0,0.0,0.0,0.0,138.0,286.0,1.0,48.0,21.0,0.0,NaN,546.0
1453,0.0,0.0,0.0,0.0,546.0,0.0,0.0,NaN,21.0,0.0,NaN,546.0
1454,0.0,0.0,0.0,0.0,546.0,0.0,0.0,NaN,21.0,0.0,NaN,546.0
1455,252.0,0.0,0.0,0.0,294.0,286.0,1.0,48.0,21.0,0.0,NaN,546.0
1456,1224.0,0.0,1.0,0.0,0.0,576.0,2.0,58.0,160.0,0.0,NaN,1224.0
1457,337.0,0.0,0.0,1.0,575.0,0.0,0.0,NaN,62.0,0.0,NaN,912.0
1458,758.0,0.0,0.0,0.0,238.0,650.0,3.0,25.0,74.0,94.0,NaN,996.0

In [384]:
for column in data1[is_null_less].columns:
    data1[column][data1[column].isnull()] = data1[column].mean()

/Users/charliecarrera/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [385]:
data1[is_null].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 12 columns):
BsmtFinSF1      2919 non-null float64
BsmtFinSF2      2919 non-null float64
BsmtFullBath    2919 non-null float64
BsmtHalfBath    2919 non-null float64
BsmtUnfSF       2919 non-null float64
GarageArea      2919 non-null float64
GarageCars      2919 non-null float64
GarageYrBlt     2760 non-null float64
LotFrontage     2433 non-null float64
MasVnrArea      2896 non-null float64
SalePrice       1460 non-null float64
TotalBsmtSF     2919 non-null float64
dtypes: float64(12)
memory usage: 296.5 KB

In [386]:
new_null = [column for column in data1.columns if data1[column].isnull().sum() > 0]

In [387]:
data1[new_null].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 4 columns):
GarageYrBlt    2760 non-null float64
LotFrontage    2433 non-null float64
MasVnrArea     2896 non-null float64
SalePrice      1460 non-null float64
dtypes: float64(4)
memory usage: 114.0 KB

In [388]:
data1['GarageYrBlt'][data1['GarageYrBlt'].isnull()] = data1['YearBuilt'][data1['GarageYrBlt'].isnull()]

/Users/charliecarrera/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [389]:
null_now = [column for column in data1.columns if data1[column].isnull().sum() > 0]

In [390]:
data1[null_now].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 3 columns):
LotFrontage    2433 non-null float64
MasVnrArea     2896 non-null float64
SalePrice      1460 non-null float64
dtypes: float64(3)
memory usage: 171.2 KB

In [391]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 79 columns):
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
3SsnPorch        2919 non-null int64
BedroomAbvGr     2919 non-null int64
BldgType         2919 non-null int64
BsmtCond         2919 non-null int64
BsmtExposure     2919 non-null int64
BsmtFinSF1       2919 non-null float64
BsmtFinSF2       2919 non-null float64
BsmtFinType1     2919 non-null int64
BsmtFinType2     2919 non-null int64
BsmtFullBath     2919 non-null float64
BsmtHalfBath     2919 non-null float64
BsmtQual         2919 non-null int64
BsmtUnfSF        2919 non-null float64
CentralAir       2919 non-null int64
Condition1       2919 non-null int64
Condition2       2919 non-null int64
Electrical       2919 non-null int64
EnclosedPorch    2919 non-null int64
ExterCond        2919 non-null int64
ExterQual        2919 non-null int64
Exterior1st      2919 non-null int64
Exterior2nd      2919 non-null int64
Fence            2919 non-null int64
FireplaceQu      2919 non-null int64
Fireplaces       2919 non-null int64
Foundation       2919 non-null int64
FullBath         2919 non-null int64
Functional       2919 non-null int64
GarageArea       2919 non-null float64
GarageCars       2919 non-null float64
GarageCond       2919 non-null int64
GarageFinish     2919 non-null int64
GarageQual       2919 non-null int64
GarageType       2919 non-null int64
GarageYrBlt      2919 non-null float64
GrLivArea        2919 non-null int64
HalfBath         2919 non-null int64
Heating          2919 non-null int64
HeatingQC        2919 non-null int64
HouseStyle       2919 non-null int64
Id               2919 non-null int64
KitchenAbvGr     2919 non-null int64
KitchenQual      2919 non-null int64
LandContour      2919 non-null int64
LandSlope        2919 non-null int64
LotArea          2919 non-null int64
LotConfig        2919 non-null int64
LotFrontage      2433 non-null float64
LotShape         2919 non-null int64
LowQualFinSF     2919 non-null int64
MSSubClass       2919 non-null int64
MSZoning         2919 non-null int64
MasVnrArea       2896 non-null float64
MasVnrType       2919 non-null int64
MiscFeature      2919 non-null int64
MiscVal          2919 non-null int64
MoSold           2919 non-null int64
Neighborhood     2919 non-null int64
OpenPorchSF      2919 non-null int64
OverallCond      2919 non-null int64
OverallQual      2919 non-null int64
PavedDrive       2919 non-null int64
PoolArea         2919 non-null int64
RoofMatl         2919 non-null int64
RoofStyle        2919 non-null int64
SaleCondition    2919 non-null int64
SalePrice        1460 non-null float64
SaleType         2919 non-null int64
ScreenPorch      2919 non-null int64
Street           2919 non-null int64
TotRmsAbvGrd     2919 non-null int64
TotalBsmtSF      2919 non-null float64
Utilities        2919 non-null int64
WoodDeckSF       2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
YrSold           2919 non-null int64
dtypes: float64(12), int64(67)
memory usage: 1.9 MB

In [392]:
data1.ix[5]['MasVnrType']

/Users/charliecarrera/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

5    1
5    1
Name: MasVnrType, dtype: int64

In [393]:
data1['MasVnrArea'][data1['MasVnrArea'].isnull()] = [data1.groupby('MasVnrType')['MasVnrArea'].mean()[i] for i in data1['MasVnrType'][data1['MasVnrArea'].isnull()]]

/Users/charliecarrera/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [394]:
data1['LotFrontage'][data1['LotFrontage'].isnull()] = [data1.groupby('LotShape')['LotFrontage'].mean()[i] for i in data1['LotShape'][data1['LotFrontage'].isnull()]]

/Users/charliecarrera/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [395]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 79 columns):
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
3SsnPorch        2919 non-null int64
BedroomAbvGr     2919 non-null int64
BldgType         2919 non-null int64
BsmtCond         2919 non-null int64
BsmtExposure     2919 non-null int64
BsmtFinSF1       2919 non-null float64
BsmtFinSF2       2919 non-null float64
BsmtFinType1     2919 non-null int64
BsmtFinType2     2919 non-null int64
BsmtFullBath     2919 non-null float64
BsmtHalfBath     2919 non-null float64
BsmtQual         2919 non-null int64
BsmtUnfSF        2919 non-null float64
CentralAir       2919 non-null int64
Condition1       2919 non-null int64
Condition2       2919 non-null int64
Electrical       2919 non-null int64
EnclosedPorch    2919 non-null int64
ExterCond        2919 non-null int64
ExterQual        2919 non-null int64
Exterior1st      2919 non-null int64
Exterior2nd      2919 non-null int64
Fence            2919 non-null int64
FireplaceQu      2919 non-null int64
Fireplaces       2919 non-null int64
Foundation       2919 non-null int64
FullBath         2919 non-null int64
Functional       2919 non-null int64
GarageArea       2919 non-null float64
GarageCars       2919 non-null float64
GarageCond       2919 non-null int64
GarageFinish     2919 non-null int64
GarageQual       2919 non-null int64
GarageType       2919 non-null int64
GarageYrBlt      2919 non-null float64
GrLivArea        2919 non-null int64
HalfBath         2919 non-null int64
Heating          2919 non-null int64
HeatingQC        2919 non-null int64
HouseStyle       2919 non-null int64
Id               2919 non-null int64
KitchenAbvGr     2919 non-null int64
KitchenQual      2919 non-null int64
LandContour      2919 non-null int64
LandSlope        2919 non-null int64
LotArea          2919 non-null int64
LotConfig        2919 non-null int64
LotFrontage      2919 non-null float64
LotShape         2919 non-null int64
LowQualFinSF     2919 non-null int64
MSSubClass       2919 non-null int64
MSZoning         2919 non-null int64
MasVnrArea       2919 non-null float64
MasVnrType       2919 non-null int64
MiscFeature      2919 non-null int64
MiscVal          2919 non-null int64
MoSold           2919 non-null int64
Neighborhood     2919 non-null int64
OpenPorchSF      2919 non-null int64
OverallCond      2919 non-null int64
OverallQual      2919 non-null int64
PavedDrive       2919 non-null int64
PoolArea         2919 non-null int64
RoofMatl         2919 non-null int64
RoofStyle        2919 non-null int64
SaleCondition    2919 non-null int64
SalePrice        1460 non-null float64
SaleType         2919 non-null int64
ScreenPorch      2919 non-null int64
Street           2919 non-null int64
TotRmsAbvGrd     2919 non-null int64
TotalBsmtSF      2919 non-null float64
Utilities        2919 non-null int64
WoodDeckSF       2919 non-null int64
YearBuilt        2919 non-null int64
YearRemodAdd     2919 non-null int64
YrSold           2919 non-null int64
dtypes: float64(12), int64(67)
memory usage: 1.9 MB

In [396]:
train_kaggle = data1[data1['SalePrice'].notnull()]

In [397]:
train_kaggle.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 0 to 1459
Data columns (total 79 columns):
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
3SsnPorch        1460 non-null int64
BedroomAbvGr     1460 non-null int64
BldgType         1460 non-null int64
BsmtCond         1460 non-null int64
BsmtExposure     1460 non-null int64
BsmtFinSF1       1460 non-null float64
BsmtFinSF2       1460 non-null float64
BsmtFinType1     1460 non-null int64
BsmtFinType2     1460 non-null int64
BsmtFullBath     1460 non-null float64
BsmtHalfBath     1460 non-null float64
BsmtQual         1460 non-null int64
BsmtUnfSF        1460 non-null float64
CentralAir       1460 non-null int64
Condition1       1460 non-null int64
Condition2       1460 non-null int64
Electrical       1460 non-null int64
EnclosedPorch    1460 non-null int64
ExterCond        1460 non-null int64
ExterQual        1460 non-null int64
Exterior1st      1460 non-null int64
Exterior2nd      1460 non-null int64
Fence            1460 non-null int64
FireplaceQu      1460 non-null int64
Fireplaces       1460 non-null int64
Foundation       1460 non-null int64
FullBath         1460 non-null int64
Functional       1460 non-null int64
GarageArea       1460 non-null float64
GarageCars       1460 non-null float64
GarageCond       1460 non-null int64
GarageFinish     1460 non-null int64
GarageQual       1460 non-null int64
GarageType       1460 non-null int64
GarageYrBlt      1460 non-null float64
GrLivArea        1460 non-null int64
HalfBath         1460 non-null int64
Heating          1460 non-null int64
HeatingQC        1460 non-null int64
HouseStyle       1460 non-null int64
Id               1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null int64
LandContour      1460 non-null int64
LandSlope        1460 non-null int64
LotArea          1460 non-null int64
LotConfig        1460 non-null int64
LotFrontage      1460 non-null float64
LotShape         1460 non-null int64
LowQualFinSF     1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null int64
MasVnrArea       1460 non-null float64
MasVnrType       1460 non-null int64
MiscFeature      1460 non-null int64
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
Neighborhood     1460 non-null int64
OpenPorchSF      1460 non-null int64
OverallCond      1460 non-null int64
OverallQual      1460 non-null int64
PavedDrive       1460 non-null int64
PoolArea         1460 non-null int64
RoofMatl         1460 non-null int64
RoofStyle        1460 non-null int64
SaleCondition    1460 non-null int64
SalePrice        1460 non-null float64
SaleType         1460 non-null int64
ScreenPorch      1460 non-null int64
Street           1460 non-null int64
TotRmsAbvGrd     1460 non-null int64
TotalBsmtSF      1460 non-null float64
Utilities        1460 non-null int64
WoodDeckSF       1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
YrSold           1460 non-null int64
dtypes: float64(12), int64(67)
memory usage: 912.5 KB

In [398]:
test_kaggle = data1[data1['SalePrice'].isnull()]

In [399]:
test_kaggle.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1459 entries, 0 to 1458
Data columns (total 79 columns):
1stFlrSF         1459 non-null int64
2ndFlrSF         1459 non-null int64
3SsnPorch        1459 non-null int64
BedroomAbvGr     1459 non-null int64
BldgType         1459 non-null int64
BsmtCond         1459 non-null int64
BsmtExposure     1459 non-null int64
BsmtFinSF1       1459 non-null float64
BsmtFinSF2       1459 non-null float64
BsmtFinType1     1459 non-null int64
BsmtFinType2     1459 non-null int64
BsmtFullBath     1459 non-null float64
BsmtHalfBath     1459 non-null float64
BsmtQual         1459 non-null int64
BsmtUnfSF        1459 non-null float64
CentralAir       1459 non-null int64
Condition1       1459 non-null int64
Condition2       1459 non-null int64
Electrical       1459 non-null int64
EnclosedPorch    1459 non-null int64
ExterCond        1459 non-null int64
ExterQual        1459 non-null int64
Exterior1st      1459 non-null int64
Exterior2nd      1459 non-null int64
Fence            1459 non-null int64
FireplaceQu      1459 non-null int64
Fireplaces       1459 non-null int64
Foundation       1459 non-null int64
FullBath         1459 non-null int64
Functional       1459 non-null int64
GarageArea       1459 non-null float64
GarageCars       1459 non-null float64
GarageCond       1459 non-null int64
GarageFinish     1459 non-null int64
GarageQual       1459 non-null int64
GarageType       1459 non-null int64
GarageYrBlt      1459 non-null float64
GrLivArea        1459 non-null int64
HalfBath         1459 non-null int64
Heating          1459 non-null int64
HeatingQC        1459 non-null int64
HouseStyle       1459 non-null int64
Id               1459 non-null int64
KitchenAbvGr     1459 non-null int64
KitchenQual      1459 non-null int64
LandContour      1459 non-null int64
LandSlope        1459 non-null int64
LotArea          1459 non-null int64
LotConfig        1459 non-null int64
LotFrontage      1459 non-null float64
LotShape         1459 non-null int64
LowQualFinSF     1459 non-null int64
MSSubClass       1459 non-null int64
MSZoning         1459 non-null int64
MasVnrArea       1459 non-null float64
MasVnrType       1459 non-null int64
MiscFeature      1459 non-null int64
MiscVal          1459 non-null int64
MoSold           1459 non-null int64
Neighborhood     1459 non-null int64
OpenPorchSF      1459 non-null int64
OverallCond      1459 non-null int64
OverallQual      1459 non-null int64
PavedDrive       1459 non-null int64
PoolArea         1459 non-null int64
RoofMatl         1459 non-null int64
RoofStyle        1459 non-null int64
SaleCondition    1459 non-null int64
SalePrice        0 non-null float64
SaleType         1459 non-null int64
ScreenPorch      1459 non-null int64
Street           1459 non-null int64
TotRmsAbvGrd     1459 non-null int64
TotalBsmtSF      1459 non-null float64
Utilities        1459 non-null int64
WoodDeckSF       1459 non-null int64
YearBuilt        1459 non-null int64
YearRemodAdd     1459 non-null int64
YrSold           1459 non-null int64
dtypes: float64(12), int64(67)
memory usage: 911.9 KB

In [400]:
test_train = train_kaggle.drop('SalePrice', axis = 1)

In [401]:
test_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1460 entries, 0 to 1459
Data columns (total 78 columns):
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
3SsnPorch        1460 non-null int64
BedroomAbvGr     1460 non-null int64
BldgType         1460 non-null int64
BsmtCond         1460 non-null int64
BsmtExposure     1460 non-null int64
BsmtFinSF1       1460 non-null float64
BsmtFinSF2       1460 non-null float64
BsmtFinType1     1460 non-null int64
BsmtFinType2     1460 non-null int64
BsmtFullBath     1460 non-null float64
BsmtHalfBath     1460 non-null float64
BsmtQual         1460 non-null int64
BsmtUnfSF        1460 non-null float64
CentralAir       1460 non-null int64
Condition1       1460 non-null int64
Condition2       1460 non-null int64
Electrical       1460 non-null int64
EnclosedPorch    1460 non-null int64
ExterCond        1460 non-null int64
ExterQual        1460 non-null int64
Exterior1st      1460 non-null int64
Exterior2nd      1460 non-null int64
Fence            1460 non-null int64
FireplaceQu      1460 non-null int64
Fireplaces       1460 non-null int64
Foundation       1460 non-null int64
FullBath         1460 non-null int64
Functional       1460 non-null int64
GarageArea       1460 non-null float64
GarageCars       1460 non-null float64
GarageCond       1460 non-null int64
GarageFinish     1460 non-null int64
GarageQual       1460 non-null int64
GarageType       1460 non-null int64
GarageYrBlt      1460 non-null float64
GrLivArea        1460 non-null int64
HalfBath         1460 non-null int64
Heating          1460 non-null int64
HeatingQC        1460 non-null int64
HouseStyle       1460 non-null int64
Id               1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null int64
LandContour      1460 non-null int64
LandSlope        1460 non-null int64
LotArea          1460 non-null int64
LotConfig        1460 non-null int64
LotFrontage      1460 non-null float64
LotShape         1460 non-null int64
LowQualFinSF     1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null int64
MasVnrArea       1460 non-null float64
MasVnrType       1460 non-null int64
MiscFeature      1460 non-null int64
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
Neighborhood     1460 non-null int64
OpenPorchSF      1460 non-null int64
OverallCond      1460 non-null int64
OverallQual      1460 non-null int64
PavedDrive       1460 non-null int64
PoolArea         1460 non-null int64
RoofMatl         1460 non-null int64
RoofStyle        1460 non-null int64
SaleCondition    1460 non-null int64
SaleType         1460 non-null int64
ScreenPorch      1460 non-null int64
Street           1460 non-null int64
TotRmsAbvGrd     1460 non-null int64
TotalBsmtSF      1460 non-null float64
Utilities        1460 non-null int64
WoodDeckSF       1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
YrSold           1460 non-null int64
dtypes: float64(11), int64(67)
memory usage: 901.1 KB

In [413]:
from sklearn.linear_model import LinearRegression
L = LinearRegression()

In [414]:
L.fit(train_kaggle.drop('SalePrice', axis = 1), train_kaggle['SalePrice'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [415]:
from sklearn.metrics import r2_score, mean_squared_error

In [416]:
r2_score(train_kaggle['SalePrice'], L.predict(train_kaggle.drop('SalePrice', axis = 1)))

0.8477035183629901

In [417]:
del test_kaggle['SalePrice']

KeyError: 'SalePrice'

In [418]:
predictions = L.predict(test_kaggle)

In [419]:
len(predictions)

1459

In [420]:
result = pd.DataFrame(columns = ['Id', 'SalePrice'])
result['Id'] = test_kaggle['Id']
result['SalePrice'] = predictions

     Id      SalePrice
0  1461  103466.042422
1  1462  167918.528337
2  1463  177304.286094
3  1464  203285.743053
4  1465  186145.314042

In [422]:
result.head()

     Id      SalePrice
0  1461  103466.042422
1  1462  167918.528337
2  1463  177304.286094
3  1464  203285.743053
4  1465  186145.314042

In [424]:
result.to_csv('SalePrice Kaggle.csv', index = False)

In [351]:
sample

        Id      SalePrice
0     1461  169277.052498
1     1462  187758.393989
2     1463  183583.683570
3     1464  179317.477511
4     1465  150730.079977
5     1466  177150.989247
6     1467  172070.659229
7     1468  175110.956520
8     1469  162011.698832
9     1470  160726.247831
10    1471  157933.279456
11    1472  145291.245020
12    1473  159672.017632
13    1474  164167.518302
14    1475  150891.638244
15    1476  179460.965187
16    1477  185034.628914
17    1478  182352.192645
18    1479  183053.458214
19    1480  187823.339254
20    1481  186544.114328
21    1482  158230.775205
22    1483  190552.829321
23    1484  147183.674872
24    1485  185855.300905
25    1486  174350.470677
26    1487  201740.620691
27    1488  162986.378896
28    1489  162330.199086
29    1490  165845.938617
...    ...            ...
1429  2890  160515.850579
1430  2891  192167.621096
1431  2892  178751.551083
1432  2893  198678.894117
1433  2894  164553.120272
1434  2895  156887.932862
1435  2896  164185.777306
1436  2897  212992.120631
1437  2898  197468.550533
1438  2899  180106.843740
1439  2900  183972.071057
1440  2901  245283.198338
1441  2902  170351.963411
1442  2903  195596.307707
1443  2904  189369.756330
1444  2905  223667.404552
1445  2906  169335.310624
1446  2907  167411.028352
1447  2908  187709.555004
1448  2909  196526.002999
1449  2910  137402.569856
1450  2911  165086.775062
1451  2912  188506.431412
1452  2913  172917.456816
1453  2914  166274.325226
1454  2915  167081.220949
1455  2916  164788.778231
1456  2917  219222.423400
1457  2918  184924.279659
1458  2919  187741.866657

[1459 rows x 2 columns]