In [685]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#This dataset contains loan characteristics of a bank's customers 
#The goal is to clean the dataset, create a model to predict whether or not a loan default occurs, and
#find the characteristics that make for a good loan recipient

In [686]:
#Creating the dataset
data = pd.read_csv('LoansTrainingSet.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [687]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256984 entries, 0 to 256983
Data columns (total 19 columns):
Loan ID                         256984 non-null object
Customer ID                     256984 non-null object
Loan Status                     256984 non-null object
Current Loan Amount             256984 non-null int64
Term                            256984 non-null object
Credit Score                    195308 non-null float64
Years in current job            256984 non-null object
Home Ownership                  256984 non-null object
Annual Income                   195308 non-null float64
Purpose                         256984 non-null object
Monthly Debt                    256984 non-null object
Years of Credit History         256984 non-null float64
Months since last delinquent    116601 non-null float64
Number of Open Accounts         256984 non-null int64
Number of Credit Problems       256984 non-null int64
Current Credit Balance          256984 non-null int64
Maximum Open Credit             256984 non-null object
Bankruptcies                    256455 non-null float64
Tax Liens                       256961 non-null float64
dtypes: float64(6), int64(4), object(9)
memory usage: 37.3+ MB

In [689]:
data.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,Fully Paid,11520,Short Term,741.0,10+ years,Home Mortgage,33694.0,Debt Consolidation,$584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,Fully Paid,3441,Short Term,734.0,4 years,Home Mortgage,42269.0,other,"$1,106.04",26.3,NaN,17,0,6262,19149,0.0,0.0
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,Fully Paid,21029,Short Term,747.0,10+ years,Home Mortgage,90126.0,Debt Consolidation,"$1,321.85",28.8,NaN,5,0,20967,28335,0.0,0.0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,Fully Paid,18743,Short Term,747.0,10+ years,Own Home,38072.0,Debt Consolidation,$751.92,26.2,NaN,9,0,22529,43915,0.0,0.0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,Fully Paid,11731,Short Term,746.0,4 years,Rent,50025.0,Debt Consolidation,$355.18,11.5,NaN,12,0,17391,37081,0.0,0.0

In [690]:
#Get rid of non-integer units in series
for ch in ['$', ',']:
    data['Monthly Debt'] = [i.replace(ch, '') for i in data['Monthly Debt']]

In [691]:
data['Monthly Debt'] = [float(i) for i in data['Monthly Debt']]

In [692]:
data['Monthly Debt']

0          584.03
1         1106.04
2         1321.85
3          751.92
4          355.18
5          561.52
6          542.29
7          542.29
8          386.36
9          741.79
10         582.84
11        1573.32
12         597.50
13         596.85
14         596.85
15         597.50
16         984.07
17         451.00
18         662.16
19         662.16
20         745.70
21         745.70
22         439.56
23         483.58
24         859.26
25         476.53
26         262.27
27        2185.81
28         777.38
29         321.85
           ...
256954    2608.66
256955    1155.73
256956     345.54
256957    1643.75
256958     286.77
256959     469.35
256960     430.13
256961     811.63
256962     620.42
256963     833.98
256964     820.96
256965     790.35
256966     790.35
256967     318.39
256968     732.67
256969     732.67
256970    1046.68
256971    1412.33
256972    1412.33
256973     707.08
256974     707.08
256975      47.11
256976      47.11
256977     982.82
256978     982.82
256979    1706.58
256980    1376.47
256981     297.96
256982     297.96
256983    2525.82
Name: Monthly Debt, Length: 256984, dtype: float64

In [693]:
data['Loan Status'].unique()

array(['Fully Paid', 'Charged Off'], dtype=object)

In [694]:
#Change 'Loan Status' unique values to integers
data1['Loan Status'] = data['Loan Status'].replace('Fully Paid', 1).replace('Charged Off', 0)

In [695]:
data1['Loan Status']

0         1
1         1
2         1
3         1
4         1
5         1
6         0
7         0
8         1
9         1
10        1
11        1
12        0
13        0
14        0
15        0
16        1
17        1
18        0
19        0
20        0
21        0
22        1
23        1
24        1
25        1
26        1
27        1
28        1
29        1
         ..
256954    1
256955    1
256956    1
256957    1
256958    1
256959    1
256960    1
256961    1
256962    1
256963    1
256964    1
256965    0
256966    0
256967    1
256968    0
256969    0
256970    1
256971    0
256972    0
256973    0
256974    0
256975    0
256976    0
256977    0
256978    0
256979    1
256980    1
256981    0
256982    0
256983    1
Name: Loan Status, Length: 256984, dtype: int64

In [696]:
#The columns 'Loan Status', 'Home Ownership', and 'Purpose' are all categorical 
#Here we create dummy variables for them so Python can interpret them
#Dummy variables represent categorical data as numeric
data2 = pd.merge(data1, (pd.get_dummies(data['Term'], drop_first = True)),left_index = True, right_index = True)

In [697]:
data3 = pd.merge(data2, (pd.get_dummies(data['Home Ownership'], drop_first = True)), left_index = True, right_index = True)

In [698]:
data4 = pd.merge(data3, (pd.get_dummies(data['Purpose'], drop_first = True)), left_index = True, right_index = True)

In [699]:
del data4['Term']
del data4['Home Ownership']
del data4['Purpose']

In [700]:
data4.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Credit Score,Years in current job,Annual Income,Monthly Debt,Years of Credit History,Months since last delinquent,...,Rent,Buy House,Buy a Car,Debt Consolidation,Educational Expenses,Home Improvements,Medical Bills,Other,Take a Trip,other
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,1,11520,741.0,10+ years,33694.0,584.03,12.3,41.0,...,0,0,0,1,0,0,0,0,0,0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,1,3441,734.0,4 years,42269.0,1106.04,26.3,NaN,...,0,0,0,0,0,0,0,0,0,1
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,1,21029,747.0,10+ years,90126.0,1321.85,28.8,NaN,...,0,0,0,1,0,0,0,0,0,0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,1,18743,747.0,10+ years,38072.0,751.92,26.2,NaN,...,0,0,0,1,0,0,0,0,0,0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,1,11731,746.0,4 years,50025.0,355.18,11.5,NaN,...,1,0,0,1,0,0,0,0,0,0

In [701]:
data4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256984 entries, 0 to 256983
Data columns (total 30 columns):
Loan ID                         256984 non-null object
Customer ID                     256984 non-null object
Loan Status                     256984 non-null int64
Current Loan Amount             256984 non-null int64
Credit Score                    195308 non-null float64
Years in current job            256984 non-null object
Annual Income                   195308 non-null float64
Monthly Debt                    256984 non-null float64
Years of Credit History         256984 non-null float64
Months since last delinquent    116601 non-null float64
Number of Open Accounts         256984 non-null int64
Number of Credit Problems       256984 non-null int64
Current Credit Balance          256984 non-null int64
Maximum Open Credit             256984 non-null object
Bankruptcies                    256455 non-null float64
Tax Liens                       256961 non-null float64
Short Term_x                    256984 non-null uint8
Short Term_y                    256984 non-null uint8
Home Mortgage                   256984 non-null uint8
Own Home                        256984 non-null uint8
Rent                            256984 non-null uint8
Buy House                       256984 non-null uint8
Buy a Car                       256984 non-null uint8
Debt Consolidation              256984 non-null uint8
Educational Expenses            256984 non-null uint8
Home Improvements               256984 non-null uint8
Medical Bills                   256984 non-null uint8
Other                           256984 non-null uint8
Take a Trip                     256984 non-null uint8
other                           256984 non-null uint8
dtypes: float64(7), int64(5), object(4), uint8(14)
memory usage: 34.8+ MB

In [702]:
data4.corr()

,Loan Status,Current Loan Amount,Credit Score,Annual Income,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,...,Rent,Buy House,Buy a Car,Debt Consolidation,Educational Expenses,Home Improvements,Medical Bills,Other,Take a Trip,other
Loan Status,1.000000,0.269804,-0.440307,0.070328,-0.016609,0.035548,0.023541,-0.020787,-0.010179,0.008838,...,-0.062959,0.003706,0.024949,-0.001793,0.000505,0.022265,-0.005133,0.014854,-0.000259,-0.018092
Current Loan Amount,0.269804,1.000000,-0.139743,0.024069,-0.001928,0.014725,0.003488,-0.003094,-0.000062,0.003138,...,-0.019448,0.001675,0.007060,-0.000173,0.002249,0.005638,-0.002055,0.005424,-0.001048,-0.005161
Credit Score,-0.440307,-0.139743,1.000000,-0.033221,0.005518,-0.011658,-0.007994,0.008124,0.000777,-0.003263,...,0.026512,-0.000005,-0.010635,0.003534,-0.000422,-0.008781,0.003071,-0.007807,-0.002141,0.003812
Annual Income,0.070328,0.024069,-0.033221,1.000000,0.454638,0.146859,-0.059675,0.140463,-0.013672,0.292165,...,-0.152658,0.008286,-0.014758,-0.031492,-0.008967,0.072842,-0.003047,-0.004447,-0.011189,-0.020287
Monthly Debt,-0.016609,-0.001928,0.005518,0.454638,1.000000,0.188646,-0.056377,0.410416,-0.052792,0.472581,...,-0.187406,-0.020118,-0.052909,0.098217,-0.024400,-0.003684,-0.012430,-0.062845,-0.016935,-0.054886
Years of Credit History,0.035548,0.014725,-0.011658,0.146859,0.188646,1.000000,-0.039695,0.128033,0.061251,0.201001,...,-0.197944,-0.009164,-0.007641,0.009894,0.003037,0.034114,0.002957,-0.033322,-0.011536,-0.014512
Months since last delinquent,0.023541,0.003488,-0.007994,-0.059675,-0.056377,-0.039695,1.000000,-0.035803,0.088612,-0.024292,...,0.048513,-0.005753,0.005373,0.015807,-0.006835,-0.006413,-0.008626,-0.004765,-0.003855,-0.003744
Number of Open Accounts,-0.020787,-0.003094,0.008124,0.140463,0.410416,0.128033,-0.035803,1.000000,-0.013731,0.222763,...,-0.131451,-0.015354,-0.039338,0.107607,-0.014989,-0.018276,-0.017824,-0.059107,-0.018508,-0.059669
Number of Credit Problems,-0.010179,-0.000062,0.000777,-0.013672,-0.052792,0.061251,0.088612,-0.013731,1.000000,-0.103814,...,-0.003146,-0.000180,-0.007838,-0.003844,-0.007293,0.023186,0.000867,-0.017318,-0.000315,0.002627
Current Credit Balance,0.008838,0.003138,-0.003263,0.292165,0.472581,0.201001,-0.024292,0.222763,-0.103814,1.000000,...,-0.157313,-0.016330,-0.030486,0.077174,-0.010286,-0.012794,-0.013754,-0.050726,-0.019384,-0.040505
Bankruptcies,0.001154,0.003576,-0.003426,-0.044837,-0.078440,0.062049,0.112907,-0.022805,0.755866,-0.117995,...,0.000976,-0.000671,-0.007643,0.005102,-0.007093,0.022360,0.000251,-0.020573,0.000649,-0.003704
Tax Liens,-0.012585,-0.003069,0.004381,0.038185,0.020557,0.020915,0.002730,0.005754,0.584917,-0.011118,...,-0.003432,0.000495,-0.003965,-0.004241,-0.003560,0.006115,-0.001961,-0.003823,-0.000748,0.001861
Short Term_x,0.183811,0.048366,-0.063124,-0.064219,-0.151294,-0.035773,0.012107,-0.080506,0.019326,-0.090077,...,0.094092,-0.003370,0.011237,-0.035947,0.013622,-0.013564,0.017970,0.030435,0.031253,0.029255
Short Term_y,0.183811,0.048366,-0.063124,-0.064219,-0.151294,-0.035773,0.012107,-0.080506,0.019326,-0.090077,...,0.094092,-0.003370,0.011237,-0.035947,0.013622,-0.013564,0.017970,0.030435,0.031253,0.029255
Home Mortgage,0.066485,0.022415,-0.027572,0.170834,0.205076,0.176821,-0.048589,0.135632,-0.001143,0.156387,...,-0.831889,-0.017014,-0.014146,-0.007765,-0.013856,0.147775,-0.009205,-0.051419,-0.075989,-0.048490
Own Home,-0.008300,-0.005950,0.002765,-0.035239,-0.034933,0.032031,0.003055,-0.009351,0.006744,-0.000808,...,-0.268603,0.005417,0.009709,-0.037329,-0.002889,0.040847,0.004181,0.004356,0.000343,0.013014
Rent,-0.062959,-0.019448,0.026512,-0.152658,-0.187406,-0.197944,0.048513,-0.131451,-0.003146,-0.157313,...,1.000000,0.014430,0.009219,0.038240,0.015823,-0.171867,0.007377,0.050376,0.018998,0.042624
Buy House,0.003706,0.001675,-0.000005,0.008286,-0.020118,-0.009164,-0.005753,-0.015354,-0.000180,-0.016330,...,0.014430,1.000000,-0.008794,-0.151696,-0.002496,-0.019210,-0.008222,-0.015301,-0.006068,-0.018764
Buy a Car,0.024949,0.007060,-0.010635,-0.014758,-0.052909,-0.007641,0.005373,-0.039338,-0.007838,-0.030486,...,0.009219,-0.008794,1.000000,-0.222735,-0.003665,-0.028206,-0.012072,-0.022466,-0.008909,-0.027551
Debt Consolidation,-0.001793,-0.000173,0.003534,-0.031492,0.098217,0.009894,0.015807,0.107607,-0.003844,0.077174,...,0.038240,-0.151696,-0.222735,1.000000,-0.063214,-0.486548,-0.208237,-0.387527,-0.153678,-0.475243
Educational Expenses,0.000505,0.002249,-0.000422,-0.008967,-0.024400,0.003037,-0.006835,-0.014989,-0.007293,-0.010286,...,0.015823,-0.002496,-0.003665,-0.063214,1.000000,-0.008005,-0.003426,-0.006376,-0.002528,-0.007819
Home Improvements,0.022265,0.005638,-0.008781,0.072842,-0.003684,0.034114,-0.006413,-0.018276,0.023186,-0.012794,...,-0.171867,-0.019210,-0.028206,-0.486548,-0.008005,1.000000,-0.026370,-0.049075,-0.019461,-0.060183
Medical Bills,-0.005133,-0.002055,0.003071,-0.003047,-0.012430,0.002957,-0.008626,-0.017824,0.000867,-0.013754,...,0.007377,-0.008222,-0.012072,-0.208237,-0.003426,-0.026370,1.000000,-0.021004,-0.008329,-0.025758
Other,0.014854,0.005424,-0.007807,-0.004447,-0.062845,-0.033322,-0.004765,-0.059107,-0.017318,-0.050726,...,0.050376,-0.015301,-0.022466,-0.387527,-0.006376,-0.049075,-0.021004,1.000000,-0.015501,-0.047935
Take a Trip,-0.000259,-0.001048,-0.002141,-0.011189,-0.016935,-0.011536,-0.003855,-0.018508,-0.000315,-0.019384,...,0.018998,-0.006068,-0.008909,-0.153678,-0.002528,-0.019461,-0.008329,-0.015501,1.000000,-0.019009
other,-0.018092,-0.005161,0.003812,-0.020287,-0.054886,-0.014512,-0.003744,-0.059669,0.002627,-0.040505,...,0.042624,-0.018764,-0.027551,-0.475243,-0.007819,-0.060183,-0.025758,-0.047935,-0.019009,1.000000

In [703]:
#Next we deal with missing values for 'Bankruptcies' and 'Tax Liens'
#Correlation map shows both variables are correlated with 'Number of Credit Problems'
#We fill missing values depending on how many credit problems that individual has had

In [704]:
#Knowing how many credit problems someone has can help us predict how many bankruptcies they have had
data4.groupby('Number of Credit Problems')['Bankruptcies'].mean()

Number of Credit Problems
0     0.000000
1     0.822141
2     0.900234
3     1.039191
4     1.058182
5     1.008000
6     1.214286
7     1.187500
8     0.916667
9     0.100000
10    0.666667
11    0.000000
Name: Bankruptcies, dtype: float64

In [705]:
for i in data4[data4['Bankruptcies'].isnull()].index:
    data4['Bankruptcies'][i] = data['Bankruptcies'][data4['Number of Credit Problems'] == data4.ix[i]['Number of Credit Problems']].mean()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [706]:
for i in data4[data4['Tax Liens'].isnull()].index:
    data4['Tax Liens'][i] = data4['Tax Liens'][data4['Number of Credit Problems'] == data4.ix[i]['Number of Credit Problems']].mean()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [707]:
#Each Loan is suppose to be unique, therefore duplicates are dropped
data5 = data4.drop_duplicates(['Loan ID'], keep = 'last')

In [710]:
#Max credit score an individual can have is 800 based off of this particular credit scoring system. 
#It appears an extra zero was added to these credit scores
data5['Credit Score'][data5['Credit Score'] > 800]

341       6600.0
349       6760.0
420       7460.0
522       7320.0
623       7270.0
846       6690.0
926       7230.0
1240      7380.0
1306      7440.0
1317      7390.0
1381      7210.0
1540      6790.0
1599      6600.0
1863      6430.0
2030      7390.0
2436      7060.0
2628      6440.0
2784      6370.0
3103      6580.0
3228      7500.0
3276      7320.0
3369      6710.0
3483      7210.0
3534      7390.0
3551      7130.0
4108      6570.0
4115      6250.0
4163      7420.0
4432      7240.0
4719      7400.0
           ...
251641    6970.0
251829    6460.0
251938    6980.0
252027    6860.0
252035    7160.0
252042    6730.0
252074    7150.0
252157    7240.0
252247    6990.0
252320    6980.0
252421    7150.0
252591    7470.0
252681    6980.0
253238    7370.0
253516    7280.0
253650    7300.0
253907    7080.0
253947    7450.0
253956    7000.0
253980    7100.0
254504    6970.0
254732    7350.0
255385    7070.0
255631    7210.0
256249    7330.0
256278    7120.0
256844    6890.0
256869    6600.0
256875    7350.0
256952    7410.0
Name: Credit Score, Length: 1631, dtype: float64

In [711]:
#We divide these values by ten to get rid of the extra zero
#This is done through list comprehension
data5['Credit Score'][data5['Credit Score'] > 800] = [i/10 for i in data5['Credit Score'][data5['Credit Score'] > 800]]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:5233: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2862: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [712]:
#There are now no more values above 800 
data5['Credit Score'].describe()

count    167406.000000
mean        723.033541
std          26.640342
min         585.000000
25%         713.000000
50%         732.000000
75%         742.000000
max         751.000000
Name: Credit Score, dtype: float64

In [713]:
#Some individuals had absurdly high loan amounts yet low income
#Delete outliers in 'Current Loan Amount'
data6 = data5.drop(data5[data5['Current Loan Amount'] > 1000000].index)

In [730]:
#Next 'Years in current job' is cleaned
data['Years in current job']

0         10+ years
1           4 years
2         10+ years
3         10+ years
4           4 years
5         10+ years
6           6 years
7           6 years
8           5 years
9               n/a
10          3 years
11          2 years
12         < 1 year
13         < 1 year
14         < 1 year
15         < 1 year
16          6 years
17          5 years
18          6 years
19          6 years
20          3 years
21          3 years
22          3 years
23        10+ years
24        10+ years
25          5 years
26        10+ years
27        10+ years
28           1 year
29        10+ years
            ...
256954    10+ years
256955       1 year
256956      4 years
256957      6 years
256958      9 years
256959      2 years
256960      2 years
256961      7 years
256962    10+ years
256963    10+ years
256964     < 1 year
256965      6 years
256966      6 years
256967      6 years
256968      5 years
256969      5 years
256970    10+ years
256971      8 years
256972      8 years
256973     < 1 year
256974     < 1 year
256975      9 years
256976      9 years
256977    10+ years
256978    10+ years
256979      2 years
256980    10+ years
256981      9 years
256982      9 years
256983    10+ years
Name: Years in current job, Length: 256984, dtype: object

In [731]:
h = []
[h.append(i.split(' ')[0]) for i in data6['Years in current job'] if type(i) == str]
len(h)

180490

In [732]:
h = [i.replace('<', '.5') for i in h]
h = [i.replace('n/a', '0') for i in h]
h = [i.replace('10+', '10') for i in h]
h = [float(i) for i in h]
h
data6['Years in current job'] = h

In [733]:
hh = list(data6['Maximum Open Credit'])
hh

[16056.0,
 19149.0,
 28335.0,
 43915.0,
 37081.0,
 4671.0,
 16954.0,
 16579.0,
 15676.0,
 41726.0,
 22800.0,
 15982.0,
 20743.0,
 101110.0,
 15866.0,
 16995.0,
 8989.0,
 9330.0,
 54068.0,
 13662.0,
 42392.0,
 225911.0,
 49563.0,
 45971.0,
 39766.0,
 17955.0,
 13975.0,
 9242.0,
 10723.0,
 28919.0,
 149693.0,
 12105.0,
 51227.0,
 25476.0,
 33025.0,
 33343.0,
 6613.0,
 8105.0,
 39230.0,
 24317.0,
 6850.0,
 31867.0,
 78316.0,
 9806.0,
 28467.0,
 14413.0,
 4009.0,
 40935.0,
 34366.0,
 15211.0,
 7811.0,
 90199.0,
 26469.0,
 9319.0,
 14650.0,
 67607.0,
 12041.0,
 4025.0,
 13306.0,
 15630.0,
 7109.0,
 15969.0,
 4428.0,
 12934.0,
 14603.0,
 17163.0,
 23588.0,
 15964.0,
 0.0,
 68767.0,
 10543.0,
 600.0,
 57569.0,
 7376.0,
 14497.0,
 106251.0,
 23216.0,
 35773.0,
 24999.0,
 19674.0,
 41904.0,
 28795.0,
 6503.0,
 18802.0,
 19542.0,
 16008.0,
 5736.0,
 21634.0,
 9902.0,
 22278.0,
 26957.0,
 14042.0,
 32795.0,
 22524.0,
 36795.0,
 17848.0,
 47809.0,
 56404.0,
 33419.0,
 36925.0,
 66010.0,
 6530.0,
 29125.0,
 18788.0,
 10555.0,
 31967.0,
 14234.0,
 31315.0,
 30606.0,
 64068.0,
 19736.0,
 59603.0,
 21207.0,
 12619.0,
 14261.0,
 20053.0,
 17327.0,
 25131.0,
 8074.0,
 10951.0,
 23201.0,
 37547.0,
 4626.0,
 0.0,
 18128.0,
 17791.0,
 13133.0,
 53477.0,
 3500.0,
 20181.0,
 8289.0,
 6232.0,
 15437.0,
 16115.0,
 26298.0,
 19736.0,
 29646.0,
 44874.0,
 6801.0,
 13310.0,
 12011.0,
 12449.0,
 30197.0,
 37406.0,
 24155.0,
 14851.0,
 8938.0,
 12502.0,
 90877.0,
 27529.0,
 18146.0,
 11099.0,
 11717.0,
 10968.0,
 28058.0,
 16394.0,
 0.0,
 5715.0,
 31372.0,
 16123.0,
 10104.0,
 32416.0,
 12565.0,
 48530.0,
 40699.0,
 38549.0,
 7596.0,
 18110.0,
 27247.0,
 4492.0,
 14675.0,
 17638.0,
 10724.0,
 19601.0,
 24923.0,
 20078.0,
 8763.0,
 93340.0,
 10120.0,
 59402.0,
 16562.0,
 38437.0,
 24917.0,
 16852.0,
 29215.0,
 19563.0,
 8825.0,
 6691.0,
 18632.0,
 15522.0,
 77867.0,
 16167.0,
 23633.0,
 63384.0,
 66205.0,
 49796.0,
 14997.0,
 5859.0,
 38845.0,
 26570.0,
 15850.0,
 12128.0,
 32418.0,
 82064.0,
 40661.0,
 30366.0,
 17568.0,
 11132.0,
 12797.0,
 18545.0,
 96924.0,
 8278.0,
 23217.0,
 3066.0,
 22628.0,
 6978.0,
 11050.0,
 17397.0,
 59356.0,
 33189.0,
 58038.0,
 21982.0,
 71458.0,
 14154.0,
 28923.0,
 8977.0,
 59079.0,
 11103.0,
 29043.0,
 5375.0,
 8589.0,
 13607.0,
 2914.0,
 18625.0,
 70548.0,
 0.0,
 18643.0,
 4330.0,
 10999.0,
 17158.0,
 16006.0,
 47857.0,
 50526.0,
 30647.0,
 17148.0,
 26005.0,
 5491.0,
 0.0,
 94528.0,
 10343.0,
 6384.0,
 33957.0,
 11890.0,
 57816.0,
 31275.0,
 28503.0,
 26651.0,
 4191.0,
 45432.0,
 44202.0,
 15433.0,
 49789.0,
 64735.0,
 42612.0,
 14011.0,
 14431.0,
 21504.0,
 22132.0,
 46783.0,
 28898.0,
 15599.0,
 14859.0,
 18785.0,
 7758.0,
 27430.0,
 8206.0,
 13147.0,
 19111.0,
 16485.0,
 10691.0,
 21149.0,
 20472.0,
 42585.0,
 325008.0,
 34148.0,
 14440.0,
 29537.0,
 98236.0,
 26879.0,
 35466.0,
 86978.0,
 41772.0,
 23142.0,
 5339.0,
 42879.0,
 14547.0,
 8838.0,
 31429.0,
 15672.0,
 38861.0,
 11525.0,
 29564.0,
 10350.0,
 21571.0,
 29899.0,
 5342.0,
 69444.0,
 16008.0,
 5176.0,
 23340.0,
 27246.0,
 21818.0,
 9378.0,
 27472.0,
 18198.0,
 11922.0,
 34782.0,
 140725.0,
 21557.0,
 16380.0,
 0.0,
 8738.0,
 25787.0,
 21797.0,
 16642.0,
 29178.0,
 33145.0,
 21063.0,
 8320.0,
 32934.0,
 20482.0,
 14945.0,
 12488.0,
 49210.0,
 5699.0,
 32604.0,
 34014.0,
 15910.0,
 5883.0,
 4928.0,
 32065.0,
 52581.0,
 19993.0,
 87108.0,
 8190.0,
 31489.0,
 11002.0,
 2324.0,
 48152.0,
 4865.0,
 16486.0,
 29639.0,
 13787.0,
 4465.0,
 42636.0,
 11247.0,
 20064.0,
 16166.0,
 7117.0,
 119500.0,
 89692.0,
 38755.0,
 17053.0,
 20734.0,
 35698.0,
 19325.0,
 34004.0,
 10472.0,
 19302.0,
 9176.0,
 21469.0,
 21837.0,
 21300.0,
 47081.0,
 33819.0,
 9905.0,
 17773.0,
 29680.0,
 20667.0,
 21968.0,
 17223.0,
 67720.0,
 9146.0,
 20906.0,
 7861.0,
 47060.0,
 45570.0,
 43573.0,
 22732.0,
 12132.0,
 226966.0,
 9723.0,
 48947.0,
 58262.0,
 13500.0,
 17582.0,
 19695.0,
 6091.0,
 162052.0,
 39451.0,
 12307.0,
 31629.0,
 2448.0,
 23249.0,
 23329.0,
 69642.0,
 87700.0,
 30218.0,
 0.0,
 33891.0,
 24976.0,
 36997.0,
 14645.0,
 46956.0,
 12457.0,
 18857.0,
 9253.0,
 39874.0,
 16086.0,
 39810.0,
 31345.0,
 27847.0,
 22653.0,
 10422.0,
 43603.0,
 19259.0,
 15911.0,
 15626.0,
 12074.0,
 6871.0,
 6026.0,
 32275.0,
 41034.0,
 27962.0,
 121744.0,
 9651.0,
 10392.0,
 23260.0,
 44768.0,
 18054.0,
 18241.0,
 3172.0,
 13311.0,
 6861.0,
 27530.0,
 31419.0,
 16215.0,
 17374.0,
 18882.0,
 91960.0,
 29467.0,
 29611.0,
 43162.0,
 7878.0,
 9208.0,
 36460.0,
 50750.0,
 40211.0,
 27774.0,
 33823.0,
 17253.0,
 10280.0,
 13437.0,
 31220.0,
 49415.0,
 34056.0,
 8436.0,
 51441.0,
 16265.0,
 9000.0,
 13483.0,
 22226.0,
 29018.0,
 19686.0,
 22864.0,
 15398.0,
 26970.0,
 11510.0,
 60386.0,
 32227.0,
 45410.0,
 14683.0,
 21427.0,
 22562.0,
 28700.0,
 28015.0,
 14518.0,
 91839.0,
 25354.0,
 7468.0,
 9373.0,
 12983.0,
 29606.0,
 27978.0,
 23339.0,
 58205.0,
 17604.0,
 94045.0,
 7905.0,
 14224.0,
 21455.0,
 49317.0,
 38524.0,
 40336.0,
 13165.0,
 13072.0,
 4232.0,
 0.0,
 18136.0,
 20553.0,
 36661.0,
 32129.0,
 27601.0,
 34441.0,
 31572.0,
 12220.0,
 46848.0,
 22840.0,
 10949.0,
 30822.0,
 19765.0,
 9663.0,
 25744.0,
 9858.0,
 22106.0,
 30346.0,
 43945.0,
 28071.0,
 5845.0,
 26973.0,
 698.0,
 18768.0,
 0.0,
 15086.0,
 19066.0,
 49850.0,
 38964.0,
 69600.0,
 51726.0,
 24181.0,
 10240.0,
 39524.0,
 3814.0,
 34779.0,
 26470.0,
 16706.0,
 34971.0,
 42563.0,
 5524.0,
 19303.0,
 21727.0,
 15733.0,
 16474.0,
 55417.0,
 9589.0,
 29678.0,
 15847.0,
 42919.0,
 156326.0,
 15607.0,
 20303.0,
 18185.0,
 17438.0,
 25894.0,
 70180.0,
 43491.0,
 37598.0,
 15906.0,
 96827.0,
 68728.0,
 35612.0,
 43057.0,
 60611.0,
 21748.0,
 9127.0,
 52303.0,
 18031.0,
 27864.0,
 23472.0,
 2349.0,
 18598.0,
 10335.0,
 23350.0,
 23262.0,
 46855.0,
 14328.0,
 24961.0,
 6151.0,
 24210.0,
 59613.0,
 43076.0,
 45274.0,
 28618.0,
 17281.0,
 5819.0,
 24103.0,
 0.0,
 8977.0,
 9864.0,
 798.0,
 17541.0,
 32717.0,
 26338.0,
 17750.0,
 50243.0,
 8120.0,
 32090.0,
 25940.0,
 58229.0,
 15530.0,
 5630.0,
 57331.0,
 6445.0,
 53349.0,
 21141.0,
 7314.0,
 39771.0,
 17155.0,
 22629.0,
 54276.0,
 6554.0,
 20677.0,
 46527.0,
 8122.0,
 27865.0,
 48219.0,
 17330.0,
 51185.0,
 10306.0,
 30791.0,
 10694.0,
 26595.0,
 782.0,
 301021.0,
 26073.0,
 49729.0,
 75742.0,
 23093.0,
 20822.0,
 44738.0,
 22687.0,
 10187.0,
 22631.0,
 12111.0,
 39964.0,
 22761.0,
 45180.0,
 14561.0,
 16487.0,
 24448.0,
 7648.0,
 13269.0,
 5456.0,
 57923.0,
 46445.0,
 34500.0,
 27344.0,
 27842.0,
 4848.0,
 152980.0,
 13536.0,
 26885.0,
 10847.0,
 10182.0,
 36110.0,
 17317.0,
 21438.0,
 13870.0,
 59774.0,
 13659.0,
 59938.0,
 7982.0,
 8779.0,
 30093.0,
 12023.0,
 34598.0,
 7024.0,
 14090.0,
 15491.0,
 25296.0,
 31333.0,
 173670.0,
 30875.0,
 4400.0,
 33574.0,
 13861.0,
 26245.0,
 30934.0,
 11239.0,
 40866.0,
 8992.0,
 16303.0,
 49272.0,
 18560.0,
 6858.0,
 26424.0,
 22787.0,
 31011.0,
 77672.0,
 71536.0,
 16959.0,
 43751.0,
 6152.0,
 37735.0,
 39413.0,
 24100.0,
 15705.0,
 20113.0,
 356570.0,
 8255.0,
 114694.0,
 26776.0,
 42117.0,
 15042.0,
 43728.0,
 14479.0,
 29228.0,
 53314.0,
 10712.0,
 19457.0,
 52636.0,
 28594.0,
 9562.0,
 9434.0,
 18411.0,
 74757.0,
 11526.0,
 18845.0,
 35645.0,
 61317.0,
 3637.0,
 6792.0,
 36353.0,
 12535.0,
 8664.0,
 2445.0,
 16585.0,
 25786.0,
 13047.0,
 145338.0,
 24039.0,
 3425.0,
 20091.0,
 35323.0,
 36278.0,
 0.0,
 98542.0,
 2690.0,
 11429.0,
 9673.0,
 15311.0,
 8408.0,
 6801.0,
 20798.0,
 30133.0,
 4793.0,
 27928.0,
 63528.0,
 34689.0,
 12015.0,
 34264.0,
 33441.0,
 24654.0,
 22260.0,
 13540.0,
 55393.0,
 17376.0,
 33583.0,
 30447.0,
 49650.0,
 24954.0,
 23933.0,
 47498.0,
 41134.0,
 17150.0,
 31953.0,
 6339.0,
 16442.0,
 36814.0,
 14858.0,
 77197.0,
 68871.0,
 28269.0,
 36083.0,
 19519.0,
 13659.0,
 10216.0,
 21423.0,
 46829.0,
 17192.0,
 35424.0,
 21068.0,
 806698.0,
 20522.0,
 10053.0,
 40637.0,
 16411.0,
 40751.0,
 23009.0,
 44036.0,
 15671.0,
 39047.0,
 8106.0,
 13844.0,
 12352.0,
 26584.0,
 46391.0,
 37844.0,
 47571.0,
 87825.0,
 13300.0,
 31571.0,
 18428.0,
 405091.0,
 20901.0,
 27424.0,
 27468.0,
 39147.0,
 8988.0,
 17934.0,
 42218.0,
 31118.0,
 6948.0,
 15808.0,
 14914.0,
 7079.0,
 28399.0,
 25999.0,
 7284.0,
 1294.0,
 9247.0,
 21322.0,
 28085.0,
 19476.0,
 11886.0,
 13618.0,
 18463.0,
 18816.0,
 9000.0,
 22761.0,
 9034.0,
 38462.0,
 76184.0,
 6829.0,
 21031.0,
 75447.0,
 12739.0,
 40928.0,
 179394.0,
 13059.0,
 22732.0,
 10162.0,
 28608.0,
 8267.0,
 15003.0,
 17188.0,
 23965.0,
 50209.0,
 59873.0,
 78410.0,
 30966.0,
 40174.0,
 20335.0,
 112386.0,
 49134.0,
 25344.0,
 27002.0,
 33088.0,
 86663.0,
 16869.0,
 11218.0,
 23565.0,
 54129.0,
 7189.0,
 16709.0,
 33425.0,
 14998.0,
 30643.0,
 34787.0,
 24515.0,
 16790.0,
 14712.0,
 20498.0,
 14950.0,
 22495.0,
 11653.0,
 43824.0,
 41734.0,
 43502.0,
 17434.0,
 19008.0,
 13791.0,
 61220.0,
 33694.0,
 23042.0,
 12848.0,
 9674.0,
 4686.0,
 23070.0,
 23635.0,
 27873.0,
 3017.0,
 71799.0,
 20519.0,
 1718.0,
 7870.0,
 3470.0,
 50114.0,
 36070.0,
 70797.0,
 92913.0,
 141190.0,
 51444.0,
 23859.0,
 66222.0,
 61230.0,
 39273.0,
 20563.0,
 15886.0,
 13450.0,
 0.0,
 24811.0,
 15337.0,
 17295.0,
 25137.0,
 31143.0,
 5843.0,
 7734.0,
 13485.0,
 8355.0,
 93949.0,
 42302.0,
 41589.0,
 16765.0,
 24243.0,
 14705.0,
 48596.0,
 79062.0,
 43108.0,
 11900.0,
 7747.0,
 80005.0,
 21462.0,
 22296.0,
 1279.0,
 26905.0,
 6279.0,
 13003.0,
 28385.0,
 24286.0,
 8999.0,
 36894.0,
 30138.0,
 25866.0,
 25156.0,
 37129.0,
 10353.0,
 31892.0,
 51577.0,
 30924.0,
 51689.0,
 7430.0,
 16500.0,
 9193.0,
 4500.0,
 40564.0,
 10622.0,
 49442.0,
 18857.0,
 30032.0,
 59273.0,
 2362.0,
 68837.0,
 38846.0,
 119833.0,
 44496.0,
 18268.0,
 13950.0,
 44816.0,
 101596.0,
 77190.0,
 9504.0,
 2559.0,
 41975.0,
 9311.0,
 7746.0,
 24724.0,
 10912.0,
 10861.0,
 8640.0,
 19388.0,
 49775.0,
 35421.0,
 12201.0,
 25497.0,
 7068.0,
 10160.0,
 36494.0,
 8241.0,
 18714.0,
 ...]

In [734]:
#Now 'Maximum Open Credit is cleaned by getting rid of strings
hh = [str(i).replace('#VALUE!', '0') for i in hh]
hh = [float(i) for i in hh]
data6['Maximum Open Credit'] = hh

In [727]:
data6['Maximum Open Credit'] = [float(i) for i in data6['Maximum Open Credit']]

In [735]:
data6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180490 entries, 0 to 256983
Data columns (total 30 columns):
Loan ID                         180490 non-null object
Customer ID                     180490 non-null object
Loan Status                     180490 non-null int64
Current Loan Amount             180490 non-null int64
Credit Score                    132196 non-null float64
Years in current job            180490 non-null float64
Annual Income                   132196 non-null float64
Monthly Debt                    180490 non-null float64
Years of Credit History         180490 non-null float64
Months since last delinquent    81733 non-null float64
Number of Open Accounts         180490 non-null int64
Number of Credit Problems       180490 non-null int64
Current Credit Balance          180490 non-null int64
Maximum Open Credit             180490 non-null float64
Bankruptcies                    180490 non-null float64
Tax Liens                       180490 non-null float64
Short Term_x                    180490 non-null uint8
Short Term_y                    180490 non-null uint8
Home Mortgage                   180490 non-null uint8
Own Home                        180490 non-null uint8
Rent                            180490 non-null uint8
Buy House                       180490 non-null uint8
Buy a Car                       180490 non-null uint8
Debt Consolidation              180490 non-null uint8
Educational Expenses            180490 non-null uint8
Home Improvements               180490 non-null uint8
Medical Bills                   180490 non-null uint8
Other                           180490 non-null uint8
Take a Trip                     180490 non-null uint8
other                           180490 non-null uint8
dtypes: float64(9), int64(5), object(2), uint8(14)
memory usage: 25.8+ MB

In [736]:
#To fill missing values for 'Annual Income', we predict it through a linear regression
#
from sklearn.linear_model import LinearRegression
L = LinearRegression()

In [737]:
from sklearn.metrics import r2_score, mean_squared_error

In [738]:
filled = data6[data6['Annual Income'].notnull()]

In [739]:
del filled['Customer ID']
del filled['Loan ID']

In [742]:
filled1 = filled.drop(filled[filled['Months since last delinquent'].isnull()].index)

In [744]:
L.fit(filled1.drop('Annual Income', axis = 1), filled1['Annual Income'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [746]:
#R Squared value is low. This model doesn't predict missing values for Income too well
#Missing values are not filled in as a result
r2_score(filled1['Annual Income'], L.predict(filled1.drop('Annual Income', axis = 1)))

0.27666836175103082

In [747]:
mean_squared_error(filled1['Annual Income'], L.predict(filled1.drop('Annual Income', axis = 1))) **.5

49769.971781574794

In [752]:
#Everytime 'Annual Income is null, so is 'Credit Score'
#These null rows are deleted
data[data['Annual Income'].isnull()]

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
7,0000afa6-8902-4f8f-b870-25a8fdad0aeb,e49c1a82-a0f7-45e8-9f46-2f75c43f9fbc,Charged Off,24613,Long Term,NaN,6 years,Rent,NaN,Business Loan,542.29,17.6,73.0,7,0,14123,16954,0.0,0.0
8,00011dfc-31c1-4178-932a-fbeb3f341efb,ef6e098c-6c83-4752-8d00-ff793e476b8c,Fully Paid,10036,Short Term,NaN,5 years,Rent,NaN,Debt Consolidation,386.36,17.7,NaN,7,0,11970,16579,0.0,0.0
12,00029f9f-0cc5-4d4e-aabc-ea4a7fe74e12,afbc2fa3-3bad-4d48-b691-829aed78bad5,Charged Off,17980,Short Term,NaN,< 1 year,Own Home,NaN,Debt Consolidation,597.50,9.9,43.0,7,0,6817,22800,0.0,0.0
20,00038a08-f058-4add-a8ed-497b91672a9e,727bb429-dfa1-41c4-a347-23230e23949f,Charged Off,16929,Long Term,NaN,3 years,Home Mortgage,NaN,Debt Consolidation,745.70,14.9,NaN,10,0,28513,101110,0.0,0.0
22,0003b749-307f-4830-9fb4-9db7ed1b1c48,998dc43c-f9ce-466e-bdaa-7057b0bbb9cd,Fully Paid,7228,Short Term,NaN,3 years,Home Mortgage,NaN,Debt Consolidation,439.56,17.8,NaN,13,1,8488,15866,1.0,0.0
26,0004d002-a494-4f8a-a528-a6d513812701,4722d542-6684-431c-afb6-ba2e847f1098,Fully Paid,4612,Short Term,NaN,10+ years,Rent,NaN,Debt Consolidation,262.27,14.0,NaN,4,0,8919,9330,0.0,0.0
38,0008255a-402e-4716-9e0a-8bdf55309781,4e25b6bf-9abc-4bbd-841e-c5a8403b68de,Fully Paid,6114,Short Term,NaN,n/a,Home Mortgage,NaN,Debt Consolidation,206.97,17.8,21.0,8,1,5772,13975,1.0,0.0
46,000a08fa-e669-46dc-9a96-9da6b96570a0,4b7782a6-b84c-4dd9-ac62-f927a68eeaa9,Charged Off,21160,Long Term,NaN,5 years,Home Mortgage,NaN,Debt Consolidation,1290.98,20.8,NaN,28,0,28175,51227,0.0,0.0
56,000c0c27-1961-4336-b760-a300e1bce9b0,881edf98-387c-4eef-ab71-317a7a5e70c1,Charged Off,6463,Short Term,NaN,1 year,Own Home,NaN,Debt Consolidation,633.29,19.9,74.0,9,0,8025,24317,0.0,0.0
57,000c16df-c24f-41cf-a90e-60301d131bb9,b07c4262-70bb-41cc-b28a-d87540577fb1,Fully Paid,7068,Short Term,NaN,n/a,Own Home,NaN,other,425.68,21.3,NaN,7,1,4178,6850,1.0,0.0
67,000ea0cb-8d0e-4284-b8c8-444ffbbe4caf,db069b01-22c0-4b77-8b0a-b5704a0fd451,Fully Paid,21075,Short Term,NaN,10+ years,Rent,NaN,Debt Consolidation,2204.13,18.0,NaN,22,0,21135,34366,0.0,0.0
72,000f1140-ef9f-42f9-9898-f9b3162bf0da,442c2d9b-3d95-44a9-bcb4-0dc80a941e3c,Charged Off,6007,Short Term,NaN,10+ years,Home Mortgage,NaN,Debt Consolidation,538.15,23.6,13.0,6,0,5077,7811,0.0,0.0
76,0011592e-e3f9-4be5-8af7-dfdb671b234f,9a5b7d14-d53a-4e16-8a74-e983d40ea039,Fully Paid,2355,Short Term,NaN,< 1 year,Home Mortgage,NaN,Other,968.38,17.1,17.0,7,0,6682,9319,0.0,0.0
81,0012f2fc-7eb6-45c2-a1ee-1d2509dfdb2a,0b0f55ef-9252-4897-b007-6b4681e444b2,Fully Paid,6288,Short Term,NaN,1 year,Rent,NaN,Buy a Car,554.56,7.8,NaN,3,0,3550,4025,0.0,0.0
101,001a909a-f61d-49ae-a243-ff596456d516,6f2514e9-2676-4d9a-9fe0-905f90377bee,Fully Paid,10444,Short Term,NaN,10+ years,Rent,NaN,Debt Consolidation,115.36,21.4,39.0,5,0,2762,10543,0.0,0.0
107,001b7e8e-ac52-42bf-90b6-b1685f0ec88c,834ae0ad-7493-40e9-a2ca-e9855f7906e8,Fully Paid,6053,Short Term,NaN,8 years,Own Home,NaN,Debt Consolidation,1072.33,32.5,46.0,14,0,507,14497,0.0,0.0
110,001cc33b-b2b7-4015-860e-b8a264f3c8e8,e7547780-1896-4bf6-933b-103e0a60b8df,Fully Paid,5070,Short Term,NaN,10+ years,Home Mortgage,NaN,Buy House,1064.31,16.9,NaN,11,0,18805,23216,0.0,0.0
111,001ce18a-3107-43cd-b4ca-9f910fb83fff,47f21078-326d-4d73-843a-03e109654e0f,Fully Paid,10371,Short Term,NaN,10+ years,Home Mortgage,NaN,Debt Consolidation,634.09,22.0,22.0,11,0,15812,35773,0.0,0.0
113,001ce813-522a-4a34-bbcc-21eaeae79aea,cc73a15c-7ad4-4101-a2af-57306c335285,Charged Off,15191,Long Term,NaN,7 years,Rent,NaN,Debt Consolidation,385.07,14.0,NaN,11,0,15655,24810,0.0,0.0
116,001ceadf-a809-4da8-b94e-73d01686b0d7,46c673c4-400c-42fd-86d8-ec8101165671,Fully Paid,9978,Short Term,NaN,7 years,Rent,NaN,Debt Consolidation,777.04,19.4,20.0,10,0,6335,19674,0.0,0.0
123,001fa6bf-4ec2-484b-931f-ed20d849c419,19f87f8b-dbf6-40f6-b6dc-e9fc6dd6e9af,Fully Paid,14198,Short Term,NaN,5 years,Home Mortgage,NaN,Debt Consolidation,1838.23,14.0,NaN,12,0,8422,19542,0.0,0.0
124,00201656-d70d-49cf-b5b0-118280383288,0d419e30-7336-4e52-980d-8c17365acc67,Charged Off,9663,Short Term,NaN,2 years,Home Mortgage,NaN,Debt Consolidation,806.79,13.3,81.0,14,0,11990,16008,0.0,0.0
130,0021a33d-62ce-44fa-9c8f-7b5396a1be81,9681f4f0-4d57-48e2-917d-a5f6d3accaab,Charged Off,11945,Short Term,NaN,5 years,Rent,NaN,Debt Consolidation,675.21,18.6,NaN,8,0,5258,22278,0.0,0.0
131,0021a33d-62ce-44fa-9c8f-7b5396a1be81,9681f4f0-4d57-48e2-917d-a5f6d3accaab,Charged Off,11945,Short Term,NaN,5 years,Rent,NaN,Debt Consolidation,675.21,18.6,NaN,8,0,5258,22278,0.0,0.0
136,00230218-35f5-41ae-825c-39f7337ebf59,5a13b38e-8684-4d17-9a7e-8a6971a49dc1,Fully Paid,14498,Short Term,NaN,10+ years,Home Mortgage,NaN,Debt Consolidation,972.74,16.3,NaN,7,0,20068,22524,0.0,0.0
150,0026a1b5-8a22-478d-a6fe-5931fa8ed673,88e7f72d-e0f0-423b-86bc-0b05f023ca7e,Charged Off,11037,Short Term,NaN,2 years,Rent,NaN,Debt Consolidation,1282.48,11.7,NaN,9,0,7152,18821,0.0,0.0
151,0026a1b5-8a22-478d-a6fe-5931fa8ed673,88e7f72d-e0f0-423b-86bc-0b05f023ca7e,Charged Off,11017,Short Term,NaN,2 years,Rent,NaN,Debt Consolidation,1280.23,11.7,NaN,9,0,7140,18788,0.0,0.0
154,00277661-a1ef-4cad-aecd-86430ed1b2d6,09de286b-9223-40e0-9dbe-72d6d0868ce7,Fully Paid,6866,Short Term,NaN,3 years,Rent,NaN,Debt Consolidation,560.57,11.5,NaN,7,0,7494,10555,0.0,0.0
156,0027a983-b2d4-4363-8191-2e5480a92549,0c8991e7-43fe-478b-94cc-ba1185f3eb05,Charged Off,10057,Short Term,NaN,3 years,Rent,NaN,Debt Consolidation,1089.87,16.4,15.0,11,0,11615,14234,0.0,0.0
157,0027a983-b2d4-4363-8191-2e5480a92549,0c8991e7-43fe-478b-94cc-ba1185f3eb05,Charged Off,10057,Short Term,NaN,3 years,Rent,NaN,Debt Consolidation,1089.87,16.4,15.0,11,0,11615,14234,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256828,ffd368d0-f1c6-45e0-969b-d5d381935de5,d553d800-9619-4663-8388-418ef44fe288,Fully Paid,29739,Short Term,NaN,3 years,Own Home,NaN,Debt Consolidation,1354.78,17.0,NaN,21,0,35950,79537,0.0,0.0
256829,ffd44cce-181c-4e79-b65f-1c5fa44df3ff,eb8e6f9d-5ce2-46b1-946b-4aed14c58b50,Fully Paid,15535,Short Term,NaN,10+ years,Own Home,NaN,Debt Consolidation,446.95,18.5,NaN,8,0,14881,17632,0.0,0.0
256830,ffd44ff9-a3cd-4d70-8a96-eb78c9909270,42f6f8c6-2ea6-47f5-b645-4ceb54350b73,Fully Paid,4983,Short Term,NaN,< 1 year,Home Mortgage,NaN,Debt Consolidation,950.79,16.3,14.0,9,0,12392,13254,0.0,0.0
256831,ffd4622c-f8f2-4e3d-8b3f-0faf07e42b09,a119c83a-2682-4ab9-878a-20d1637df1ff,Fully Paid,9811,Short Term,NaN,9 years,Rent,NaN,Debt Consolidation,691.12,18.1,44.0,9,0,4233,7882,0.0,0.0
256841,ffd96650-9b20-4d7a-a5c8-1af0b02120c2,9d2546a9-72d3-4ac5-9a57-76d803f228c3,Fully Paid,24388,Long Term,NaN,10+ years,Own Home,NaN,Debt Consolidation,627.56,23.7,NaN,7,0,4234,8553,0.0,0.0
256842,ffd9ae62-5455-4048-bec5-f233d2e62b57,6c5e1ff0-8733-4e86-8277-ac0024b36f76,Fully Paid,25411,Short Term,NaN,10+ years,Home Mortgage,NaN,Debt Consolidation,1837.07,21.8,NaN,16,0,33469,40915,0.0,0.0
256845,ffda589a-0175-4ea5-8ace-c3cc12a380fa,ef185a7b-a395-47a5-a9c3-bb15509dde16,Fully Paid,4852,Short Term,NaN,3 years,Home Mortgage,NaN,Other,652.80,9.9,NaN,8,0,7147,7986,0.0,0.0
256858,ffdfd7b0-bfa9-4b5f-bccf-cef97575011b,2e59e451-338e-45c3-8488-3656bc145506,Charged Off,14855,Long Term,NaN,4 years,Own Home,NaN,Debt Consolidation,728.65,10.9,28.0,22,0,15825,28411,0.0,0.0
256859,ffdfd7b0-bfa9-4b5f-bccf-cef97575011b,2e59e451-338e-45c3-8488-3656bc145506,Charged Off,14855,Long Term,NaN,4 years,Own Home,NaN,Debt Consolidation,728.65,10.9,28.0,22,0,15825,28411,0.0,0.0
256871,ffe2af51-6df5-417e-a930-31ffbd765d83,39012100-1900-4cb2-b4a6-eb6f86d2e43c,Fully Paid,10532,Short Term,NaN,10+ years,Home Mortgage,NaN,Debt Consolidation,791.04,15.0,37.0,13,0,12871,23880,0.0,0.0
256872,ffe2d7ea-a352-4a1f-98fb-de36926257d7,34963d5b-8d62-4822-88f1-c03a189891f0,Fully Paid,14732,Short Term,NaN,n/a,Home Mortgage,NaN,Debt Consolidation,938.30,26.4,NaN,11,0,6200,60784,0.0,0.0
256881,ffe612f1-1acd-4c28-83d7-278e6312ec97,ba1882c0-4f11-4ce5-aeec-e4f23d638dcf,Fully Paid,12044,Long Term,NaN,2 years,Rent,NaN,other,1746.44,17.7,74.0,18,1,8055,39100,1.0,0.0
256883,ffe6bc75-4463-47c1-9c71-8b73532b01f7,c1751dc8-72b2-4c4d-acf3-fb142f7cd67e,Fully Paid,33089,Long Term,NaN,< 1 year,Home Mortgage,NaN,Home Improvements,2715.51,20.5,NaN,10,0,38,19204,0.0,0.0
256888,ffe912df-1a07-4a5d-9e63-458a9304e8b6,f187b4e7-44ff-4e2c-92af-6a2ea71f3da3,Fully Paid,4903,Short Term,NaN,7 years,Rent,NaN,Debt Consolidation,263.67,10.5,NaN,10,1,4801,11972,1.0,0.0
256893,ffea733e-2ec3-45cd-ba92-ccf97037f5e6,869118c0-5868-4acc-8bd2-7ccfc8695cc3,Charged Off,35025,Long Term,NaN,6 years,Home Mortgage,NaN,Home Improvements,780.55,10.8,NaN,9,0,14180,19425,0.0,0.0
256899,ffeb9116-ec14-4a59-ae6d-649aaaa6cf26,057f219a-7405-4d43-9b0c-be7eed5debe3,Fully Paid,34311,Long Term,NaN,10+ years,Rent,NaN,Debt Consolidation,481.08,20.8,NaN,3,0,24305,35585,0.0,0.0
256904,ffec6c08-26b1-404d-9d4a-add00d3e5673,d1d24882-9496-4654-85c6-cd7b8750f492,Fully Paid,7038,Short Term,NaN,10+ years,Home Mortgage,NaN,Other,2252.10,23.2,NaN,24,0,28894,53114,0.0,0.0
256906,ffecc7a8-e40e-41ac-adb4-311504841935,e4128b1e-00d6-49a9-9f36-d87e50e1419a,Fully Paid,7340,Short Term,NaN,10+ years,Rent,NaN,Debt Consolidation,220.04,26.4,NaN,4,1,6690,9682,0.0,1.0
256910,ffedd0f5-9ce5-4136-a72d-78e7310deea0,64278634-4e52-4b4d-beb7-d90f533a77a4,Charged Off,12089,Short Term,NaN,4 years,Rent,NaN,Debt Consolidation,1708.38,11.4,25.0,10,0,6925,9978,0.0,0.0
256921,ffefc3aa-ee03-40bf-918c-8ce988032c1f,5fff7668-071e-45ba-ae09-596c6ebfa864,Fully Paid,14630,Short Term,NaN,2 years,Home Mortgage,NaN,Debt Consolidation,998.71,24.3,3.0,20,0,19532,43992,0.0,0.0
256926,fff118b9-a83d-4b0b-94ca-a4df96e0fa8f,4ef9be81-6156-46fd-aafd-0d8c0b8af01b,Fully Paid,10393,Short Term,NaN,10+ years,Rent,NaN,Debt Consolidation,647.97,31.3,NaN,8,1,8997,44320,1.0,0.0
256927,fff142bd-1430-4bb9-9eac-a5b45436a5b4,819e9ff5-f8d4-4c6f-b5c1-9d274b93f159,Charged Off,24503,Long Term,NaN,9 years,Rent,NaN,Debt Consolidation,1053.61,20.1,21.0,12,0,3695,18201,0.0,0.0
256928,fff142bd-1430-4bb9-9eac-a5b45436a5b4,819e9ff5-f8d4-4c6f-b5c1-9d274b93f159,Charged Off,24658,Long Term,NaN,9 years,Rent,NaN,Debt Consolidation,1060.27,20.1,21.0,12,0,3718,18317,0.0,0.0
256936,fff2779e-9fe7-4db5-b566-48f43b58aa68,7ddd16c2-bf65-4b01-8b48-bbda8793c206,Charged Off,9976,Short Term,NaN,1 year,Home Mortgage,NaN,Debt Consolidation,1340.53,10.4,16.0,16,0,6539,17074,0.0,0.0
256939,fff34c5f-1973-4890-b081-582da99f9809,c3ad19eb-2f85-4aa7-a6c2-980faa2c9c76,Fully Paid,30462,Short Term,NaN,6 years,Rent,NaN,Debt Consolidation,2028.84,22.7,29.0,11,0,14184,17577,0.0,0.0
256959,fff9b38f-9a27-49d0-8d49-6306f41529eb,f8579c88-cbda-48ce-a542-42fbefccd01d,Fully Paid,9753,Short Term,NaN,2 years,Own Home,NaN,Debt Consolidation,469.35,23.2,80.0,7,1,5022,9248,1.0,0.0
256962,fffaa912-faa8-4bdf-8ff1-fd5884e51c66,d059bcea-3016-48d3-b7e0-c6e618e1f2c3,Fully Paid,6655,Short Term,NaN,10+ years,Rent,NaN,Debt Consolidation,620.42,11.1,62.0,15,0,7114,18336,0.0,0.0
256965,fffc297d-74f0-4d42-ad90-cdea2bd9aac0,b8cae6f0-6c9b-4982-bef2-e3cdf48add59,Charged Off,11524,Short Term,NaN,6 years,Home Mortgage,NaN,Debt Consolidation,790.35,21.4,NaN,23,0,12818,19160,0.0,0.0
256973,fffe36ec-97a6-460a-a236-640b7e0669f0,6520de3e-5961-47b1-bced-6a8132acb5cc,Charged Off,10575,Long Term,NaN,< 1 year,Rent,NaN,Debt Consolidation,707.08,14.8,NaN,18,0,20183,23496,0.0,0.0
256979,fffef5b7-be99-4666-ac70-2a397d2ee435,7211a8e3-cba4-4132-b939-222eed8a662c,Fully Paid,3911,Short Term,NaN,2 years,Rent,NaN,Debt Consolidation,1706.58,19.9,NaN,16,0,43992,44080,0.0,0.0

In [760]:
data7 = data6
del data7['Months since last delinquent']
data8 = data7.drop(data7[data7['Annual Income'].isnull()].index)

In [761]:
data8.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Credit Score,Years in current job,Annual Income,Monthly Debt,Years of Credit History,Number of Open Accounts,...,Rent,Buy House,Buy a Car,Debt Consolidation,Educational Expenses,Home Improvements,Medical Bills,Other,Take a Trip,other
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,1,11520,741.0,10.0,33694.0,584.03,12.3,10,...,0,0,0,1,0,0,0,0,0,0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,1,3441,734.0,4.0,42269.0,1106.04,26.3,17,...,0,0,0,0,0,0,0,0,0,1
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,1,21029,747.0,10.0,90126.0,1321.85,28.8,5,...,0,0,0,1,0,0,0,0,0,0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,1,18743,747.0,10.0,38072.0,751.92,26.2,9,...,0,0,0,1,0,0,0,0,0,0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,1,11731,746.0,4.0,50025.0,355.18,11.5,12,...,1,0,0,1,0,0,0,0,0,0

In [612]:
data8.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 132196 entries, 0 to 256983
Data columns (total 29 columns):
Loan ID                      132196 non-null object
Customer ID                  132196 non-null object
Loan Status                  132196 non-null int64
Current Loan Amount          132196 non-null int64
Credit Score                 132196 non-null float64
Years in current job         132196 non-null float64
Annual Income                132196 non-null float64
Monthly Debt                 132196 non-null float64
Years of Credit History      132196 non-null float64
Number of Open Accounts      132196 non-null int64
Number of Credit Problems    132196 non-null int64
Current Credit Balance       132196 non-null int64
Maximum Open Credit          132196 non-null float64
Bankruptcies                 132196 non-null float64
Tax Liens                    132196 non-null float64
Short Term                   132196 non-null uint8
Fully Paid                   132196 non-null uint8
Home Mortgage                132196 non-null uint8
Own Home                     132196 non-null uint8
Rent                         132196 non-null uint8
Buy House                    132196 non-null uint8
Buy a Car                    132196 non-null uint8
Debt Consolidation           132196 non-null uint8
Educational Expenses         132196 non-null uint8
Home Improvements            132196 non-null uint8
Medical Bills                132196 non-null uint8
Other                        132196 non-null uint8
Take a Trip                  132196 non-null uint8
other                        132196 non-null uint8
dtypes: float64(8), int64(5), object(2), uint8(14)
memory usage: 17.9+ MB

In [762]:
del data8['Loan ID']
del data8['Customer ID']

In [775]:
#Predictions are created for 'Loan Status' aka whether or not the loan was paid off
#'Loan Status' is categorical, calls for a classification algorithm 
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()

In [776]:
gbc.fit(data8.drop('Loan Status', axis = 1), data8['Loan Status'])

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [770]:
#75% accuracy score means 
accuracy_score(data8['Loan Status'], gbc.predict(data8.drop('Loan Status', axis = 1)))

0.75739054131743777

In [777]:
print(gbc.feature_importances_)

[ 0.10438967  0.18943464  0.04284989  0.18065884  0.10127577  0.0714165
  0.03295017  0.00468396  0.07069356  0.09599793  0.01642792  0.00726124
  0.01304626  0.01581257  0.00846362  0.          0.02838365  0.          0.0027543
  0.00769752  0.00249725  0.00094808  0.          0.00115457  0.          0.0012021 ]

In [779]:
gbc.feature_importances_

array([ 0.10438967,  0.18943464,  0.04284989,  0.18065884,  0.10127577,
        0.0714165 ,  0.03295017,  0.00468396,  0.07069356,  0.09599793,
        0.01642792,  0.00726124,  0.01304626,  0.01581257,  0.00846362,
        0.        ,  0.02838365,  0.        ,  0.0027543 ,  0.00769752,
        0.00249725,  0.00094808,  0.        ,  0.00115457,  0.        ,
        0.0012021 ])

In [538]:
data8.sort_values('Loan Status', ascending = False)

,Loan Status,Current Loan Amount,Credit Score,Years in current job,Annual Income,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,...,Rent,Buy House,Buy a Car,Debt Consolidation,Educational Expenses,Home Improvements,Medical Bills,Other,Take a Trip,other
0,1,11520,741.0,10.0,33694.0,584.03,12.3,10,0,6760,...,0,0,0,1,0,0,0,0,0,0
159496,1,15350,737.0,4.0,76748.0,541.07,31.8,13,0,18439,...,1,0,0,0,0,0,1,0,0,0
159515,1,14786,738.0,10.0,65056.0,414.19,31.2,16,0,20773,...,0,0,0,1,0,0,0,0,0,0
159514,1,3614,744.0,10.0,63915.0,1715.04,24.5,14,0,82557,...,0,0,0,1,0,0,0,0,0,0
159513,1,21197,738.0,9.0,110025.0,2356.36,27.6,20,0,47225,...,1,0,0,1,0,0,0,0,0,0
159511,1,19886,750.0,7.0,107384.0,826.86,19.9,10,0,22886,...,0,0,0,1,0,0,0,0,0,0
159510,1,35830,690.0,6.0,168911.0,1407.59,19.7,17,0,20844,...,0,0,0,1,0,0,0,0,0,0
159506,1,22725,726.0,10.0,45806.0,801.60,21.6,6,0,23993,...,1,0,0,1,0,0,0,0,0,0
159505,1,995,721.0,1.0,55709.0,566.37,10.0,5,0,27359,...,1,0,0,0,0,0,0,0,1,0
159503,1,23527,724.0,0.5,127439.0,1592.99,13.6,12,0,62376,...,0,0,0,1,0,0,0,0,0,0
159500,1,15730,725.0,10.0,60952.0,1056.51,18.1,12,0,9589,...,0,0,0,1,0,0,0,0,0,0
159499,1,26305,733.0,10.0,70280.0,1511.02,20.0,6,0,27406,...,1,0,0,1,0,0,0,0,0,0
159498,1,8030,739.0,0.5,126466.0,2539.86,16.7,15,0,50304,...,0,0,0,1,0,0,0,0,0,0
159495,1,8968,717.0,6.0,39856.0,803.77,17.8,19,0,14610,...,1,0,0,1,0,0,0,0,0,0
159517,1,9576,730.0,7.0,42893.0,425.35,11.4,7,0,398,...,1,0,0,0,0,0,0,1,0,0
159494,1,11984,744.0,1.0,59922.0,1158.49,14.0,10,0,16603,...,0,0,0,1,0,0,0,0,0,0
159491,1,8334,735.0,7.0,35719.0,279.80,12.1,12,0,6949,...,1,0,0,1,0,0,0,0,0,0
159490,1,32573,599.0,0.5,86522.0,1117.57,26.6,13,0,17726,...,1,0,0,1,0,0,0,0,0,0
159487,1,11719,743.0,0.5,77190.0,1145.00,15.9,23,0,13940,...,1,0,0,1,0,0,0,0,0,0
159486,1,12154,740.0,1.0,101280.0,1046.56,16.7,10,0,17270,...,1,0,0,1,0,0,0,0,0,0
159485,1,13576,729.0,10.0,71183.0,605.06,7.4,11,0,10067,...,1,0,0,1,0,0,0,0,0,0
159478,1,4978,712.0,2.0,54758.0,926.33,38.0,20,0,23909,...,1,0,0,1,0,0,0,0,0,0
159476,1,7302,740.0,10.0,81128.0,1156.07,22.1,13,0,40500,...,1,0,0,1,0,0,0,0,0,0
159470,1,10127,736.0,4.0,95194.0,720.30,25.7,15,0,11195,...,1,0,0,1,0,0,0,0,0,0
159469,1,18437,685.0,2.0,148011.0,576.02,10.6,7,2,7523,...,0,0,0,0,0,0,0,0,0,1
159468,1,12209,740.0,3.0,61044.0,859.70,12.2,8,0,13963,...,0,0,0,1,0,0,0,0,0,0
159516,1,4538,700.0,2.0,53955.0,1371.35,18.5,8,0,10750,...,0,0,0,1,0,0,0,0,0,0
159518,1,11818,743.0,10.0,34832.0,702.44,27.4,11,0,17200,...,0,0,0,1,0,0,0,0,0,0
159610,1,6342,727.0,0.5,39028.0,510.61,11.3,11,1,3040,...,0,0,0,1,0,0,0,0,0,0
159559,1,5936,678.0,0.5,25722.0,514.44,15.9,7,0,14339,...,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210274,0,10022,684.0,10.0,50110.0,337.82,12.3,14,1,8602,...,1,0,0,0,0,0,0,0,0,1
210272,0,9231,694.0,0.0,96368.0,619.97,16.0,20,0,9904,...,1,0,0,0,0,0,0,0,0,1
177539,0,12268,724.0,1.0,38847.0,780.19,13.2,9,0,11387,...,1,0,0,1,0,0,0,0,0,0
177542,0,19754,742.0,6.0,96795.0,1298.66,11.0,14,0,8908,...,0,0,0,0,0,1,0,0,0,0
177544,0,12932,687.0,4.0,41782.0,602.35,36.7,11,1,12264,...,1,0,0,1,0,0,0,0,0,0
60180,0,16793,742.0,2.0,69146.0,1480.88,14.1,19,0,17752,...,1,0,0,1,0,0,0,0,0,0
210261,0,15099,727.0,1.0,47310.0,591.38,15.2,8,1,3248,...,0,0,0,0,0,1,0,0,0,0
154959,0,7814,736.0,1.0,39068.0,719.51,5.3,9,0,7009,...,1,0,0,1,0,0,0,0,0,0
136796,0,7990,746.0,3.0,58929.0,825.01,14.0,18,2,16261,...,1,0,0,1,0,0,0,0,0,0
60176,0,11119,699.0,1.0,53851.0,190.27,12.0,3,0,7734,...,0,0,0,1,0,0,0,0,0,0
210254,0,20148,725.0,10.0,105777.0,2230.13,23.5,22,0,12738,...,0,0,0,1,0,0,0,0,0,0
35136,0,19734,680.0,10.0,118404.0,1548.13,18.5,11,1,7977,...,0,0,0,1,0,0,0,0,0,0
210248,0,4944,731.0,4.0,39548.0,549.72,15.2,11,0,9455,...,1,0,0,0,0,0,0,0,0,1
210244,0,23850,737.0,1.0,66606.0,860.32,24.3,7,0,28999,...,1,0,0,1,0,0,0,0,0,0
177570,0,14500,662.0,10.0,49426.0,807.29,14.8,6,0,17358,...,0,0,0,1,0,0,0,0,0,0
136800,0,17870,723.0,10.0,74460.0,1433.36,19.5,11,0,28580,...,0,0,0,1,0,0,0,0,0,0
177554,0,11209,746.0,7.0,134508.0,1950.37,18.2,9,0,24055,...,1,0,0,1,0,0,0,0,0,0
35147,0,9958,723.0,0.0,40126.0,732.29,9.1,7,0,14288,...,1,0,0,1,0,0,0,0,0,0
35150,0,35196,652.0,1.0,110616.0,1419.58,19.2,16,0,128912,...,0,0,0,1,0,0,0,0,0,0
210230,0,24690,671.0,7.0,59256.0,1175.24,11.6,8,0,17381,...,0,0,0,1,0,0,0,0,0,0
136805,0,7931,744.0,10.0,39656.0,432.91,22.6,6,0,3753,...,1,0,0,1,0,0,0,0,0,0
154951,0,16288,726.0,10.0,81440.0,1554.15,20.0,11,0,18840,...,0,0,0,1,0,0,0,0,0,0
177561,0,6671,683.0,3.0,52974.0,755.32,18.4,19,1,15416,...,0,0,0,0,0,0,1,0,0,0
210223,0,10314,712.0,10.0,64557.0,1468.67,12.1,8,0,9693,...,0,0,0,1,0,0,0,0,0,0
60161,0,13810,731.0,10.0,50306.0,515.64,29.7,5,0,14744,...,0,0,0,1,0,0,0,0,0,0
136815,0,7348,717.0,8.0,71435.0,1119.15,15.1,11,1,12747,...,0,0,0,1,0,0,0,0,0,0
210214,0,6166,708.0,10.0,36094.0,757.97,17.5,8,1,2581,...,0,0,0,0,0,0,0,0,0,1
77148,0,4829,717.0,2.0,48288.0,83.70,9.9,3,0,4049,...,1,1,0,0,0,0,0,0,0,0
77152,0,8042,709.0,0.5,43228.0,385.45,10.8,11,0,4036,...,0,0,1,0,0,0,0,0,0,0
162914,0,10144,744.0,10.0,91296.0,1202.06,19.8,8,0,1323,...,0,0,0,0,0,1,0,0,0,0

5 Questions
What is your credit score?
How many credit problems have you had in the past?
How much debt a month do you pay off?
What is your annual income?
Why do you need this loan?